/* Generado por split de data/plants.js — Hytech Tools */

import {
  BRANCH_METAL, BRANCH_PEX, BRANCH_B10A, BRANCH_A1, BRANCH_A13, BRANCH_A15, BRANCH_2A24, BRANCH_B3, BRANCH_PRFV1, BRANCH_Y2, BRANCH_AG0F, BRANCH_AP0H,
} from "./branches";

const c = (...a) => a;
const v = (...a) => a;


const AC1 = {
  designT: ["-29 a 38", "50", "100", "150", "200"], designP: ["20", "19,6", "18", "16,1", "14,1"],
  comps: [
    c("Seamless Pipe", "API 5L Gr. B", "80", "", "ASME B36.10M", "PE", '½"–1½"', "(1)(2)"),
    c("", "", "40", "", "", "BE", '2"–6"', "(1)(2)"), c("", "", "20", "", "", "BE", '8"–12"', "(1)(2)"),
    c("SAWL Pipe (100% RX)", "API 5L Gr. B", "10", "", "ASME B36.10M", "BE", '14"–18"', "(1)(2)"),
    c("", "", "20", "", "", "BE", '20"–24"', "(1)(2)"),
    c("Seamless Pipe (Nipple)", "ASTM A106 Gr.B", "80", "", "ASME B36.10", "PExNPT", '½"–1½"', "(4)(13)"),
    c("Forged Fittings", "ASTM A-105", "", "3000#", "ASME B16.11", "SW", '½"–1½"', "(18)"),
    c("Hexagonal Head Plug", "ASTM A-105", "", "3000#", "ASME B16.11", "NPT", '½"–1½"', "(4)(12)(13)"),
    c("Wrought Pipe Fittings", "ASTM A-234 Gr. WPB", "", "", "ASME B16.9", "BW", '2"–24"', "(5)"),
    c("Flange", "ASTM A-105", "", "150#", "ASME B16.5", "SW/RF", '½"–1½"', "(5)"),
    c("", "", "", "150#", "", "WN/RF", '2"–24"', "(5)"),
    c("Blind Flange", "ASTM A-105", "", "150#", "ASME B16.5", "BLIND RF", '½"–24"', "(5)"),
    c("Orifice Flange", "ASTM A-105", "", "300#", "ASME B16.36", "WN/RF", '1"–24"', "(5)(16)"),
    c("Gaskets", "304 SS Flexible Graphite filler", "", "150#/300#", "ASME B16.20", "—", '½"–24"', "(10)"),
    c("Stud Bolts", "ASTM A-193 Gr. B7-ZINC", "", "", "ASME B18.2.1", "—", "—", "(11)(17)"),
    c("Nuts", "ASTM A-194 Gr. 2H-ZINC", "", "", "ASME B18.2.2", "—", "—", ""),
    c("Spectacle Blind", "ASTM A-516 Gr. 70", "", "150#", "ASME B16.48", "RF", '1"–12"', "(7)(14)(15)"),
    c("Paddle & Spacer Blind", "ASTM A-516 Gr. 70", "", "150#", "", "RF", '14"–24"', ""),
    c("Drip Ring", "ASTM A-516 Gr. 70", "", "150#", "", "RF", '1"–12"', ""),
    c("Dielectric Joint", "Ver Nota 9", "", "150#", "ASME B16.21", "RF", '½"–24"', "(9)"),
    c("Olet Fittings", "ASTM A-105", "", "3000#", "MSS SP-97", "SW-NPT", '½"–1½"', "(5)(13)"),
    c("", "", "", "3000#", "", "BW-NPT", '2"–24"', "(5)(13)"),
    c("Swage Nipple", "ASTM A234 Gr. WPB", "", "", "MSS SP-95", "BW-PE", '1"–4"', "(4)(5)"),
  ],
  valves: [
    v("Ball", "RCJ8SW0", "Reduced", "—", "800#", "PE", '½"–1½"', "(4)"),
    v("Ball", "FCJ8SW0", "Full", "—", "800#", "PE", '½"–1½"', "(4)"),
    v("Ball", "VBA1WC005", "Full", "—", "2000WOG", "PExNPT-F", '½"–1½"', "(3)"),
    v("Ball", "RCC1RW0", "Reduced", "—", "150#", "RF", '2"–6"', ""),
    v("Ball", "FCC1RW0", "Full", "—", "150#", "RF", '2"–6"', ""),
    v("Ball", "VBA01C020", "Reduced", "—", "150#", "RF", '8"–24"', ""),
    v("Ball", "VBA01C018", "Full", "—", "150#", "RF", '8"–24"', ""),
    v("Gate", "ECB8SH0", "—", "—", "800#", "SW", '½"–1½"', ""),
    v("Gate", "ECB1RH0", "—", "—", "150#", "RF", '2"–12"', "HW/Gear Box ≥12\""),
    v("Gate", "ECB1RG0", "—", "—", "150#", "RF", '14"–24"', "Gear Box"),
    v("Globe", "GCB8SH0", "—", "—", "800#", "SW", '½"–1½"', ""),
    v("Globe", "GCB1RH0", "—", "—", "150#", "RF", '2"–12"', "HW/Gear Box ≥8\""),
    v("Globe", "GCB1RG0", "—", "—", "150#", "RF", '14"–24"', "Gear Box"),
    v("Butterfly", "BCJ1W00", "—", "Wafer", "150#", "-", '3"–12"', "Operator: By Vendor"),
    v("Butterfly", "BCJ1L00", "—", "Lug", "150#", "-", '14"–24"', "Operator: By Vendor"),
    v("Check", "CCB8SP0", "—", "Piston", "800#", "SW", '½"–1½"', "(2)"),
    v("Check", "CCB1WD0", "—", "Dual-Plate", "150#", "RF", '2"–12"', ""),
    v("Check", "CCB1LD0", "—", "Dual-Plate", "150#", "-", '14"–24"', "Lug Type"),
  ],
  branch: BRANCH_METAL,
  notes: [
    "Extremos biselados según ASME B16.25.",
    "Cañería enterrada: coating externo (3LPE/3LPP por NAG 108) según temperatura de servicio.",
    "Extremo NPT según ASME B1.20.1.", "El bore debe coincidir con el schedule de la cañería.",
    "Bridas y extremos bridados: cara serrada spiral 125–250 AARH máx.",
    "Junta dieléctrica: sólo tipo Pikotek VCS (no Micarta).",
    "Gaskets, sellos y empaquetaduras: libres de asbesto.",
    "Espárragos roscados en toda su longitud, con dos tuercas pesadas.",
    "Tapones hexagonales roscados sólo para venteos y drenajes.",
    "Fittings roscados sobre process piping: sólo termopozos y venteos de prueba hidráulica.",
  ],
};
const BC1 = {
  designT: ["-29 a 38", "50", "100", "150", "200"], designP: ["52,1", "51,1", "47,5", "46", "44,7"],
  comps: [
    c("Seamless Pipe", "ASTM A106 Gr. B", "80", "", "ASME B36.10M", "PE", '½"–1½"', "(2)"),
    c("", "ASTM A106 Gr B", "40", "", "", "BE", '2"', "(2)"), c("", "", "40", "", "", "BE", '3"–4"', "(2)"),
    c("", "", "40", "", "", "BE", '6"', "(2)"), c("", "", "30", "", "", "BE", '8"–10"', "(2)"),
    c("", "", "STD", "", "", "BE", '12"', "(2)"),
    c("SAWL Pipe (100% RX)", "API 5L Gr. B SAWL", "30", "", "ASME B36.10M", "BE", '14"', "(2)(7)(12)"),
    c("", "", "XS", "", "", "BE", '16"–18"', "(2)(7)(12)"), c("", "", "30", "", "", "BE", '20"', "(2)(7)(12)"),
    c("", "", "15,88", "", "", "BE", '24"', "(2)(7)(12)"), c("", "", "Nota 13", "", "", "BE", '30"', "(13)"),
    c("", "", "Nota 13", "", "", "BE", '36"', "(13)"),
    c("SMLS Pipe Niple", "ASTM A106 Gr B", "160", "", "ASME B36.10M", "NPTxPE", '½"–¾"', "(6)"),
    c("", "", "80", "", "", "NPTxPE", '1"–1½"', "(6)"),
    c("Forged Fittings", "ASTM A105", "", "3000#", "ASME B16.11", "SW", '½"–1½"', "(3)(12)"),
    c("Wrought Pipe Fittings", "ASTM A234 WPB", "", "", "ASME B16.9", "BW", '2"–36"', "(3)(12)"),
    c("Flange", "ASTM A105", "", "300#", "ASME B16.5", "SW/RF", '½"–1½"', "(4)(5)(12)"),
    c("", "", "", "300#", "", "WN/RF", '2"–24"', "(4)(5)(12)"),
    c("", "", "", "300#", "ASME B16.47 Serie A", "RF", '26"–36"', "(4)(5)(12)"),
    c("Blind Flange", "ASTM A105", "", "300#", "ASME B16.5", "RF", '½"–24"', "(4)(5)(12)"),
    c("", "", "", "300#", "ASME B16.47 Serie A", "RF", '26"–36"', "(4)(5)(12)"),
    c("Orifice Flange", "ASTM A-105", "", "300#", "ASME B16.36", "WN RF", '2"–24"', "(5)(12)"),
    c("Spiral Wound Gasket", "304 SS Flexible Graphite filler", "", "300#", "ASME B16.20", "RF", '½"–36"', "(10)"),
    c("Stud Bolts", "ASTM A-193 Gr.B7-ZINC", "", "", "ASME B18.2.1", "—", "—", "(11)(14)"),
    c("Nuts", "ASTM A-194 Gr.2H-ZINC", "", "", "ASME B18.2.2", "—", "—", ""),
    c("Spectacle Blind", "ASTM A516 Gr.70", "", "300#", "ASME B16.48", "RF", '1"–12"', "(15)(16)(17)"),
    c("Paddle & Spacer Blind", "ASTM A516 Gr.70", "", "300#", "ASME B16.48", "RF", '14"–24"', "(15)(16)(17)"),
    c("Drip Ring", "ASTM A516 Gr.70", "", "300#", "", "RF", '1"–12"', "(15)(16)(17)"),
    c("Dielectric Joint", "Ver Nota 9", "", "300#", "ASME B16.21", "RF", '½"–24"', "(9)"),
    c("Swage Nipple", "ASTM A105 / A234 WPB", "", "", "MSS SP-95", "SW-BW", '½"–4"', "(6)"),
    c("Olet Fittings", "ASTM A105", "", "6000#/3000#", "MSS SP-97", "SW-BW", '½"–24"', "(5)(6)"),
  ],
  valves: [
    v("Ball", "VBA1WC004", "Full", "—", "1500WOG", "PE", '½"–1½"', "5"),
    v("Ball", "VBA1WC001", "Reduced", "—", "1500WOG", "PE", '½"–1½"', "5"),
    v("Ball", "VBA1WC005", "Full", "—", "2000WOG", "NPT-F x PE", '½"–1½"', "4"),
    v("Ball", "VBA03C018", "Full", "—", "300#", "RF", '2"–4"', ""),
    v("Ball", "VBA03C019", "Reduced", "—", "300#", "RF", '2"–4"', ""),
    v("Ball", "VBA04C001", "Full", "—", "300#", "RF", '4"–36"', "3"),
    v("Ball", "VBA04C002", "Reduced", "—", "300#", "RF", '6"–36"', "3"),
    v("Butterfly", "VBY03C003", "—", "Wafer/Lug", "300#", "-", '3"–24"', "Wrench/Gear box ≥4\""),
    v("Check", "VCP08C001", "—", "Piston", "800#", "SW", '½"–1½"', "2"),
    v("Check", "VCK03C010", "—", "Swing", "300#", "RF", '2"–12"', ""),
    v("Check", "VCK03C007", "—", "Dual Plate", "300#", "-", '14"–24"', "Wafer Type"),
    v("Gate", "VGA08C007", "—", "—", "800#", "SW", '½"–1½"', ""),
    v("Gate", "VGA04C001", "—", "—", "300#", "RF", '2"–36"', "HW/Gear Box ≥10\""),
    v("Globe", "VGL08C004", "—", "—", "800#", "SW", '½"–1½"', ""),
    v("Globe", "VGL03C006", "—", "—", "300#", "RF", '2"–12"', "HW/Gear Box ≥8\""),
  ],
  branch: BRANCH_METAL,
  notes: [
    "Estándar dimensional: ASME B16.5 (bridas), B16.9 (BW), B16.11 (forjados), B16.10 (válvulas).",
    "Cañería enterrada: coating externo (3LPE/3LPP por NAG 108) según temperatura.",
    "El espesor de los fittings reductores debe igualar la pared más gruesa.",
    "Bridas y extremos bridados: cara serrada spiral 125–250 AARH máx.",
    "Cañería SAWL soldada (costura recta) con 100% de radiografía.",
    "Toda soldadura de cañería de espesor mayor a 3/4\" debe relevarse de tensiones.",
    "Junta dieléctrica: sólo tipo Pikotek VCS.",
    "Schedule para cañerías de 30\" y mayores: definido por proyecto (SAWL API 5L Gr.B).",
  ],
};
const AP0X = {
  designT: ["0 a 60"], designP: ["16,3"],
  comps: [
    c("Pipe", "PEX (Crosslinked PE) PE-100", "SDR 6 (S2.5)", "", "ISO 14531 / DIN 16892/16893", "—", '2"–16"', "(1)(2)(12)"),
    c("Jointing Method", "Electrofusión (con coupling)", "", "", "—", "—", "—", "(2)(6)"),
    c("Fittings", "Electrofusión HDPE PE-100 reforzado con metal", "", "", "ISO 14531 P2&3", "—", '2"–16"', "(2)(3)(4)(17)(18)"),
    c("Flange", "Flanged coupler ASTM A-536 65-45-12", "", "150#", "ASME B16.5", "FF", '2"–16"', "(5)"),
    c("Flange Lap-Joint", "ASTM A105 galvanizado (con stub end)", "", "150#", "ASME B16.5", "FF", '2"–16"', "(16)"),
    c("Closures", "Blind Flange ASTM A105 (PTFE lined)", "", "150#", "ASME B16.5", "FF", '2"–16"', ""),
    c("Spectacle Blind", "ASTM A-516 Gr. 70 (PTFE lined)", "", "150#", "ASME B16.48", "FF", '2"–12"', ""),
    c("Paddle & Spacer", "ASTM A-516 Gr. 70 (PTFE lined)", "", "150#", "ASME B16.48", "FF", '14"–16"', ""),
    c("Bolts & Nuts", "A193 GrB7-ZINC / A194 Gr2H-ZINC", "", "", "ASME B18.2.1/2", "—", "—", "(11)(14)(15)"),
    c("Gasket", "Full Face, PTFE expandido e=3,2mm", "", "150#", "ASME B16.21", "FF", '2"–16"', "(13)"),
  ],
  valves: [
    v("Ball", "VBA01C028", "Reduced", "—", "150#", "FF", '2"–6"', "(3)(5)"),
    v("Ball", "VBA01C029", "Reduced", "—", "150#", "FF", '8"–16"', "(3)(5)"),
    v("Gate", "VGA01C011", "—", "—", "150#", "FF", '2"–16"', "(4)(5) HW/Gear box ≥12\""),
    v("Globe", "VGL01C011", "—", "—", "150#", "FF", '2"–10"', "(3)(4)(5) HW/Gear box ≥8\""),
    v("Butterfly", "VBY01C010", "—", "Lug", "150#", "FF", '3"–12"', "(2)(5) HW/Gear box ≥8\""),
    v("Check", "VCK01C014", "—", "Swing", "150#", "FF", '2"–16"', "(3)(4)(5)"),
  ],
  branch: BRANCH_PEX,
  notes: [
    "El espesor de pared de la cañería lo confirma el proveedor final según la clase de presión.",
    "Cañería y fittings PEX sobre superficie: protegidos contra UV.",
    "Fittings por electrofusión, compatibles con ISO 14531 Parte 2&3.",
    "El rating de presión de cañería y fittings debe registrarse en la documentación del fabricante.",
    "Algunas derivaciones bridadas pueden ser de acero inoxidable según el proveedor.",
    "Temperatura de servicio de fittings de electrofusión PE-100 limitada a 40°C; a mayor temperatura, fittings reforzados con metal.",
  ],
};

const AC3 = {
  designT: ["-29 a 38", "100", "150", "200"], designP: ["20", "18", "16,1", "14,1"],
  comps: [
    c("Seamless Pipe", "ASTM A106 Gr.B", "160", "", "ASME B36.10M", "PE", '½"', "(14)(5)"),
    c("", "API 5L Gr.B", "XS", "", "", "PE", '¾"–1½"', ""),
    c("", "", "XS", "", "", "BE", '2"', ""),
    c("", "", "40", "", "", "BE", '3"–6"', ""),
    c("", "", "30", "", "", "BE", '8"–12"', ""),
    c("", "", "20", "", "", "BE", '14"–24"', "(1)(2)(3)"),
    c("", "", "STD", "", "", "BE", '26"', ""),
    c("SAWL Pipe (100% RX)", "API 5L Gr.B SAWL", "XS", "", "ASME B36.10M", "BE", '30"', ""),
    c("", "", "XS", "", "", "BE", '36"', ""),
    c("Seamless Pipe (Nipple)", "ASTM A106 Gr.B", "XXS", "", "ASME B36.10", "PExNPT", '½"–1½"', "(14)"),
    c("Forged Fittings", "ASTM A105", "", "6000#", "ASME B16.11", "SW", '½"', "(16)"),
    c("", "", "", "3000#", "", "SW", '1"–1½"', ""),
    c("Hexagonal Head Plug", "ASTM A105", "", "3000#", "ASME B16.11", "NPT", '½"–1½"', "(4)"),
    c("Wrought Pipe Fittings", "ASTM A234 WPB", "", "", "ASME B16.9", "BW", '2"–36"', "(6)"),
    c("Flange SW", "ASTM A105", "", "150#", "ASME B16.5", "RF", '½"–1½"', "(6)(7)"),
    c("Flange WN", "ASTM A105", "", "150#", "ASME B16.5", "RF", '2"–24"', "(6)(7)"),
    c("Flange WN", "ASTM A105", "", "150#", "ASME B16.47", "RF / Series A", '26"–36"', "(6)(7)"),
    c("Blind Flange", "ASTM A105", "", "150#", "ASME B16.5", "RF", '½"–24"', "(7)"),
    c("Blind Flange", "ASTM A105", "", "150#", "ASME B16.47", "RF / Series A", '26"–36"', "(7)"),
    c("Orifice Flange", "ASTM A105", "", "300#", "ASME B16.36", "WN / RF", '2"–24"', "(6)(7)"),
    c("Spiral Wound Gasket", "304 SS Flexible Graphite filler, 4,5mm Nom Thk., 3,2mm Compressed Thk. / CS Zinc outer ring 304 SS inner ring", "", "150#", "ASME B16.20", "—", '½"–36"', "(11)"),
    c("Stud Bolts", "ASTM A-193 Gr.B7-ZINC", "", "", "ASME B18.2.1", "—", "—", "(12)(13)"),
    c("Nuts", "ASTM A-194 Gr.2H-ZINC", "", "", "ASME B18.2.2", "—", "—", ""),
    c("Spectacle Blind", "ASTM A516 Gr.70", "", "150#", "ASME B16.48", "RF", '1"–12"', ""),
    c("Paddle & Spacer Blind", "ASTM A516 Gr.70", "", "150#", "ASME B16.48", "RF", '14"–24"', ""),
    c("Drip Ring", "ASTM A516 Gr.70", "", "150#", "", "RF", '1"–12"', "(8)(19)(15)"),
    c("Dielectric Joint", "Ver Nota 10", "", "150#", "ASME B16.21", "RF", '½"–36"', "(10)"),
    c("Olet Fittings", "ASTM A105", "", "6000#", "MSS SP-97", "SW-NPT", '½"', ""),
    c("", "", "", "3000#", "", "SW-NPT", '1"–1½"', "(6)(14)"),
    c("", "", "", "3000#", "", "BW", '2"–36"', ""),
    c("Swage Nipple", "ASTM A234 WPB", "", "", "MSS SP-95", "BW-PE", '½"–4"', "(6)"),
    c("Branch Reinforcement", "ASTM A-106 Gr.B", "", "", "ASME B31.3", "—", '6"–14"', ""),
  ],
  valves: [
    v("Ball", "VBA1WC001", "Reduced", "—", "1500 WOG", "PE", '½"–1½"', "(4)"),
    v("Ball", "VBA1WC004", "Full", "—", "1500 WOG", "PE", '½"–1½"', "(4)"),
    v("Ball", "VBA1WC005", "Full", "—", "2000WOG", "NPT-F x PE", '½"–1½"', "(3)"),
    v("Ball", "VBA01C019", "Reduced", "—", "150#", "RF", '2"–4"', ""),
    v("Ball", "FCC1RW0", "Full", "—", "150#", "RF", '2"–4"', ""),
    v("Ball", "VBA01C020", "Reduced", "—", "150#", "RF", '6"–24"', ""),
    v("Ball", "VBA01C018", "Full", "—", "150#", "RF", '6"–24"', ""),
    v("Gate", "ECB8SH0", "—", "—", "800#", "SW", '½"–1½"', ""),
    v("Gate", "VGA01C005", "—", "—", "150#", "RF", '2"–36"', "HW/Gear Box ≥12\""),
    v("Globe", "VGL08C004", "—", "—", "800#", "SW", '½"–1½"', ""),
    v("Globe", "VGL01C006", "—", "—", "150#", "RF", '2"–10"', "HW/Gear Box ≥8\""),
    v("Butterfly", "BCJ1W00", "—", "Wafer", "150#", "-", '3"–12"', "Operator: By Vendor"),
    v("Butterfly", "BCJ1L00", "—", "Lug", "150#", "-", '14"–24"', "Operator: By Vendor"),
    v("Check", "VCP08C001", "—", "Piston", "800#", "SW", '½"–1½"', "(2)"),
    v("Check", "VCK01C011", "—", "Swing", "150#", "RF", '2"–12"', ""),
    v("Check", "VCK01C007", "—", "Dual-Plate", "150#", "-", '14"–24"', "Wafer Type"),
  ],
  branch: BRANCH_A1,
  notes: [
    "Extremos biselados según ASME B16.25.",
    "Cañería enterrada: coating externo, a elegir según temperatura de servicio (3LPE fusionado -40 a 85°C, o 3LPP fusionado -20 a 100°C, según NAG 108) — el proveedor debe certificar la temperatura máxima de operación.",
    "Costura recta con 100% de radiografía.",
    "Tapones hexagonales roscados sólo para venteos y drenajes. Deben roscarse más allá de la válvula de bloqueo, fuera del process piping.",
    "Las conexiones roscadas no se consideran en la definición del schedule de cañería de esta clase.",
    "El bore debe coincidir con el schedule de la cañería.",
    "Bridas y extremos bridados: cara serrada spiral 125–250 AARH máx.",
    "Tap hole: ½\" diám. hasta 2\" diám. de cañería, ¾\" para diámetros mayores — tipo socket weld.",
    "Derivación soldada a 45° permitida sólo para drenajes abiertos y antorcha. Requisitos de refuerzo según código de diseño.",
    "Junta dieléctrica: sólo tipo Pikotek VCS. No se permite tipo Micarta. Incluye manguito aislante, doble aislación y arandelas de acero para tipo Pikotek.",
    "Gaskets, sellos, asientos y empaquetaduras: libres de materiales con asbesto.",
    "Espárragos roscados en toda su longitud, con dos tuercas hexagonales semiterminadas pesadas.",
    "Ver Nota General 2.",
    "Fittings roscados sobre process piping: sólo para termowells y venteos de prueba hidráulica.",
    "Oreja de izaje requerida en tamaños 12\" y mayores.",
    "Ver Nota General 8.",
    "Ver Nota General 1.",
    "Ver Nota General 7.",
    "Espesor mínimo de drip ring: 38,1 mm.",
    "NPT según ASME B1.20.1.",
  ],
};

const AL1 = {
  designT: ["-45 a 38", "50", "100", "150", "200"], designP: ["20", "19,6", "18", "16,1", "14,1"],
  comps: [
    c("Seamless Pipe", "ASTM A333 Gr.6", "80", "", "ASME B36.10M", "PE", '½"–1½"', "(13)"),
    c("", "", "40", "", "", "BE", '2"–6"', "(1)(2)"),
    c("", "", "20", "", "", "BE", '8"–12"', "(1)(2)"),
    c("", "", "10", "", "", "BE", '14"–18"', "(1)(2)"),
    c("", "", "20", "", "", "BE", '20"–24"', "(1)(2)"),
    c("Smls Pipe Straight Nipple", "ASTM A333 Gr.6", "80", "", "ASME B36.10M", "PExNPT", '½"–1½"', "(4)(13)"),
    c("Forged Fittings", "ASTM A350 Gr.LF2-Class 1", "", "3000#", "ASME B16.11", "SW", '½"–1½"', "(15)"),
    c("", "", "", "3000#", "", "NPT", '½"–1½"', "(4)(13)(15)"),
    c("Wrought Pipe Fittings", "ASTM A420 WPL6", "", "", "ASME B16.9", "BW", '2"–24"', "(5)"),
    c("Flange", "ASTM A350 Gr.LF2-Class 1", "", "150#", "ASME B16.5", "SW / RF", '½"–1½"', "(5)(6)"),
    c("Flange", "ASTM A350 Gr.LF2-Class 1", "", "150#", "ASME B16.5", "WN / RF", '2"–24"', "(5)(6)"),
    c("Blind Flange", "ASTM A350 Gr.LF2-Class 1", "", "150#", "ASME B16.5", "BLIND RF", '½"–24"', "(6)"),
    c("Orifice Flange", "ASTM A350 Gr.LF2-Class 1", "", "300#", "ASME B16.36", "WN / RF", '1"–24"', "(5)(6)(12)"),
    c("Gaskets", "304 SS Flexible Graphite filler, 4,5mm Nom Thk., 3,2mm Compressed Thk. / CS Zinc outer ring 304 SS inner ring", "", "150#/300#", "ASME B16.20", "—", '½"–24"', "(10)"),
    c("Stud Bolts", "ASTM A-320 Gr.L7-ZINC", "", "", "ASME B18.2.1", "—", "—", "(11)(8)"),
    c("Nuts", "ASTM A-194 Gr.4-ZINC", "", "", "ASME B18.2.2", "—", "—", ""),
    c("Spectacle Blind", "ASTM A-516 Gr.70", "", "150#", "ASME B16.48", "RF", '1"–12"', ""),
    c("Paddle & Spacer Blind", "ASTM A-516 Gr.70", "", "150#", "", "RF", '14"–24"', ""),
    c("Drip Ring", "ASTM A-516 Gr.70", "", "150#", "", "RF", '1"–24"', "(7)(14)(17)"),
    c("Dielectric Joint", "Ver Nota 9", "", "150#", "ASME B16.21", "RF", '½"–24"', "(9)"),
    c("Olet Fittings", "ASTM A350 Gr.LF2-Class 1", "", "3000#", "MSS SP-97", "SW-NPT", '½"–1½"', "(4)(5)(13)"),
    c("", "", "", "3000#", "", "BW", '2"–24"', "(4)(5)(13)"),
    c("Swage Nipple", "ASTM A333 Gr.6", "", "", "MSS SP-95", "BW-PE", '½"–4"', "(5)"),
    c("Branch Reinforcement", "ASTM A333 Gr.6", "", "", "ASME B31.3", "—", '6"–14"', ""),
  ],
  valves: [
    v("Ball", "RLJ8SW0", "Reduced", "—", "800#", "PE", '½"–1½"', "(4)"),
    v("Ball", "FLJ8SW0", "Full", "—", "800#", "PE", '½"–1½"', "(4)"),
    v("Ball", "VBA1WC006", "Full", "—", "800#", "NPT-F x PE", '½"–1½"', "(3)"),
    v("Ball", "RLF1RW0", "Reduced", "—", "150#", "RF", '2"–6"', ""),
    v("Ball", "FLF1RW0", "Full", "—", "150#", "RF", '2"–6"', ""),
    v("Ball", "RLF1RG0", "Reduced", "—", "150#", "RF", '8"–24"', ""),
    v("Ball", "FLF1RG0", "Full", "—", "150#", "RF", '8"–24"', ""),
    v("Gate", "ELD8SH0", "Reduced", "—", "800#", "SW", '½"–1½"', ""),
    v("Gate", "ELG1RH0", "—", "—", "150#", "RF", '2"–12"', "HW/Gear Box ≥12\""),
    v("Gate", "ELG1RG0", "—", "—", "150#", "RF", '14"–24"', "Gear Box"),
    v("Globe", "GLD8SH0", "—", "—", "800#", "SW", '½"–1½"', ""),
    v("Globe", "GLG1RH0", "—", "—", "150#", "RF", '2"–12"', "HW/Gear Box ≥8\""),
    v("Globe", "GLG1RG0", "—", "—", "150#", "RF", '14"–24"', "Gear Box"),
    v("Butterfly", "BLJ1W00", "—", "Wafer", "150#", "-", '3"–12"', "Operator: By Vendor"),
    v("Butterfly", "BLJ1L00", "—", "Lug", "150#", "-", '14"–24"', "Operator: By Vendor"),
    v("Check", "VCP08L001", "—", "Piston", "800#", "SW", '½"–1½"', "(2)"),
    v("Check", "CLG1WD1", "—", "Dual-Plate", "150#", "RF", '2"–12"', ""),
    v("Check", "CLG1LD0", "—", "Dual-Plate", "150#", "-", '14"–24"', "Lug Type"),
  ],
  branch: BRANCH_B10A,
  notes: [
    "Extremos biselados según ASME B16.25.",
    "Cañería enterrada: coating externo, a elegir según temperatura de servicio (3LPE fusionado -40 a 85°C, o 3LPP fusionado -20 a 100°C, según NAG 108) — el proveedor debe certificar la temperatura máxima de operación.",
    "Derivación soldada a 45° permitida sólo para drenajes abiertos y antorcha. Requisitos de refuerzo según código de diseño.",
    "NPT según ASME B1.20.1.",
    "El bore debe coincidir con el schedule de la cañería.",
    "Bridas y extremos bridados: cara serrada spiral 125–250 AARH máx.",
    "Tap hole: ½\" diám. hasta 2\" diám. de cañería, ¾\" para diámetros mayores — tipo socket weld.",
    "Ver Nota General 2.",
    "Junta dieléctrica: sólo tipo Pikotek VCS. No se permite tipo Micarta. Incluye manguito aislante, doble aislación y arandelas de acero para tipo Pikotek.",
    "Gaskets, sellos, asientos y empaquetaduras: libres de materiales con asbesto.",
    "Espárragos roscados en toda su longitud, con dos tuercas hexagonales semiterminadas pesadas.",
    "Ver Nota General 7.",
    "Fittings roscados sobre process piping: sólo para termowells y venteos de prueba hidráulica.",
    "Espesor mínimo de drip ring: 38,1 mm.",
    "Ver Nota General 1.",
    "Oreja de izaje requerida en tamaños 12\" y mayores.",
    "Se requiere ensayo de impacto a -45°C.",
  ],
};

const AC3F = {
  designT: ["0 a 38", "50"], designP: ["20", "19,6"],
  comps: [
    c("Seamless Pipe", "ASTM A53 Gr.B — Hot Dip Galv.", "XS", "", "", "NPT", '½"–2"', "(12)(7)"),
    c("", "API 5L Gr.B", "STD", "", "ASME B36.10M", "BE", '3"–12"', "(1)"),
    c("SAWL Pipe (100% RX)", "API 5L Gr.B", "STD", "", "", "BE", '14"–24"', "(1)(3)"),
    c("Smls Pipe Nipple", "ASTM A53 Gr.B — Hot Dip Galv.", "XS", "", "ASME B36.10M", "NPT", '½"–2"', "(12)(7)"),
    c("Forged Fittings", "ASTM A105 — Hot Dip Galv.", "", "3000#", "ASME B16.11", "NPT", '½"–2"', "(7)"),
    c("Wrought Pipe Fittings", "ASTM A234 WPB", "", "", "ASME B16.9", "BW", '3"–24"', "(5)"),
    c("Flange Threaded", "ASTM A105 — Hot Dip Galv.", "", "150#", "ASME B16.5", "NPT / RF", '½"–2"', "(5)(6)(7)"),
    c("Flange WN", "ASTM A105", "", "150#", "ASME B16.5", "WN / RF", '3"–24"', "(5)(6)"),
    c("Blind Flange", "ASTM A105 — Hot Dip Galv.", "", "150#", "ASME B16.5", "RF", '½"–2"', "(6)(7)"),
    c("Blind Flange", "ASTM A105", "", "150#", "ASME B16.5", "RF", '3"–24"', "(6)"),
    c("Orifice Flange", "ASTM A105", "", "300#", "ASME B16.5", "WN / RF", '3"–24"', "(6)(14)"),
    c("Spiral Wound Gaskets", "304 SS Flexible Graphite filler, 4,5mm Nom Thk., 3,2mm Compressed Thk. / CS Zinc outer ring 304 SS inner ring", "", "150#/300#", "ASME B16.20", "—", '½"–24"', "(10)"),
    c("Stud Bolts", "ASTM A-193 Gr.B7-ZINC", "", "", "ASME B18.2.1", "—", "—", "(11)(13)"),
    c("Nuts", "ASTM A-194 Gr.2H-ZINC", "", "", "ASME B18.2.2", "—", "—", ""),
    c("Spectacle Blind", "ASTM A516 Gr.70 ZINC", "", "150#", "ASME B16.48", "RF", '½"–12"', ""),
    c("Paddle & Spacer Blind", "ASTM A516 Gr.70 ZINC", "", "150#", "", "RF", '14"–24"', ""),
    c("Dielectric Joint", "Ver Nota 9", "", "150#", "ASME B16.21", "RF", '½"–24"', "(9)"),
    c("Olet Fittings", "ASTM A105", "", "3000#", "MSS SP-97", "NPT", '½"–2"', "(15)"),
    c("", "", "", "", "MSS SP-97", "BW", '3"–14"', "(5)"),
    c("Swage Nipple", "ASTM A234 WPB / Hot Dip Galv.", "", "", "MSS SP-95", "NPT / BW-NPT", '½"–4"', "(5)(7)"),
  ],
  valves: [
    v("Ball", "VBA10N001N", "Reduced", "—", "600 WOG", "NPT-F", '½"–2"', ""),
    v("Ball", "VBA10N002N", "Full", "—", "600 WOG", "NPT-F", '½"–2"', ""),
    v("Ball", "RCC1RW0", "Reduced", "—", "150#", "RF", '2"–6"', ""),
    v("Ball", "FCC1RW0", "Full", "—", "150#", "RF", '2"–6"', ""),
    v("Ball", "VBA01C020", "Reduced", "—", "150#", "RF", '8"–24"', ""),
    v("Ball", "VBA01C018", "Full", "—", "150#", "RF", '8"–24"', ""),
    v("Gate", "ECB8NH0", "—", "—", "800#", "NPT-F", '½"–1½"', ""),
    v("Gate", "ECB1RH0", "—", "—", "150#", "RF", '2"–12"', "HW/Gear Box ≥12\""),
    v("Gate", "ECB1RG0", "—", "—", "150#", "RF", '14"–24"', "Gear Box"),
    v("Globe", "GCB8NH0", "—", "—", "800#", "NPT-F", '½"–1½"', ""),
    v("Globe", "GCB1RH0", "—", "—", "150#", "RF", '2"–12"', "HW/Gear Box ≥8\""),
    v("Globe", "GCB1RG0", "—", "—", "150#", "RF", '14"–24"', "Gear Box"),
    v("Butterfly", "BCJ1W00", "—", "Wafer", "150#", "-", '3"–12"', "Operator: By Vendor"),
    v("Butterfly", "BCJ1L00", "—", "Lug", "150#", "-", '14"–24"', "Operator: By Vendor"),
    v("Check", "CBN8NS0", "—", "Swing", "800#", "NPT-F", '½"–1½"', ""),
    v("Check", "CCB1WD0", "—", "Dual-Plate", "150#", "RF", '2"–12"', ""),
    v("Check", "CCB1LD0", "—", "Dual-Plate", "150#", "-", '14"–24"', "Lug Type"),
  ],
  branch: BRANCH_A13,
  notes: [
    "Extremos biselados según ASME B16.25.",
    "Cañería enterrada: se diseñará y construirá con cañería y fittings de HDPE según la clase AP0HF.",
    "Costura recta con 100% de radiografía.",
    "Ver Nota General 1.",
    "El bore debe coincidir con el schedule de la cañería.",
    "Bridas y extremos bridados: cara serrada spiral 125–250 AARH máx.",
    "Galvanizado en caliente según ASTM A153.",
    "Todo el equipamiento, partes y accesorios deben estar listados UL o aprobados FM.",
    "Junta dieléctrica: sólo tipo Pikotek VCS. No se permite tipo Micarta. Incluye manguito aislante, doble aislación y arandelas de acero para tipo Pikotek.",
    "Gaskets, sellos, asientos y empaquetaduras: libres de materiales con asbesto.",
    "Espárragos roscados en toda su longitud, con dos tuercas hexagonales semiterminadas pesadas.",
    "Sobreespesor de corrosión para diámetros ≤2\": 0mm por tratamiento galvanizado en caliente.",
    "Ver Nota General 2.",
    "Tap holes: conexión NPTF ½\".",
    "NPT según ASME B1.20.1.",
  ],
};

const AG0F = {
  designT: ["-29 a 38"], designP: ["14"],
  comps: [
    c("Seamless Pipe", "ASTM A53 Gr.B — Hot Dip Galv.", "XS", "", "ASME B36.10M", "NPT", '½"–2"', "(1)"),
    c("", "", "STD", "", "", "GROOVE", '3"–6"', "(1)(11)"),
    c("Smls Pipe Nipple", "ASTM A53 Gr.B — Hot Dip Galv.", "XS", "", "ASME B36.10M", "NPT", '½"–2"', "(1)"),
    c("Forged Fittings", "ASTM A105 — Hot Dip Galv.", "", "3000#", "ASME B16.11", "NPT", '½"–2"', "(1)"),
    c("Forged Fittings", "ASTM A395 Gr.60-40-18 Galv.", "", "", "Manuf. Std.", "GROOVED / NPT", '3"–6"', "(1)(7)(11)(12)"),
    c("Bushing Reducer Hex.", "ASTM A105 — Hot Dip Galv.", "", "", "BS 3799", "NPT", '½"–6"', "(1)(2)"),
    c("Flange", "ASTM A105 — Hot Dip Galv.", "", "150#", "ASME B16.5", "NPT / RF", '½"–2"', "(1)(5)(6)"),
    c("Flange", "ASTM A395 Gr.60-40-18 Galv.", "", "150#", "ASME B16.5", "GROOVED / FF", '3"–6"', "(1)(11)(12)"),
    c("Blind Flange", "ASTM A105 — Hot Dip Galv.", "", "150#", "ASME B16.5", "RF", '½"–2"', "(1)"),
    c("Blind Flange", "ASTM A395 Gr.60-40-18 Galv.", "", "150#", "ASME B16.5", "FF", '3"–6"', ""),
    c("Spiral Wound Gaskets", "304 SS Flexible Graphite filler, 4,5mm Nom Thk., 3,2mm Compressed Thk. / CS Zinc outer ring 304 SS inner ring", "", "150#", "ASME B16.20", "—", '½"–2"', "(10)"),
    c("Flat Face Gasket", "Asbestos-Free Fiber Compound, NBR Binder. Compressed synthetic fiber, 2mm thk.", "", "150#", "ASME B16.21", "—", '3"–6"', "(10)"),
    c("Stud Bolts", "ASTM A-193 Gr.B7-ZINC", "", "", "ASME B18.2.1", "—", "—", "(2)(8)"),
    c("Nuts", "ASTM A-194 Gr.2H-ZINC", "", "", "ASME B18.2.2", "—", "—", ""),
    c("Dielectric Joint", "Ver Nota 9", "", "150#", "ASME B16.21", "RF", '½"–6"', "(9)"),
    c("Concentric Reducer", "ASTM A395 Gr.60-40-18 Galv.", "", "", "Manuf. Std.", "GROOVExNPT", '½"–6"', "(1)(11)(12)"),
    c("Clamp Coupling", "ASTM A395 Gr.60-40-18 Galv.", "", "", "Manuf. Std.", "—", '3"–6"', "(1)(11)(12)"),
    c("Swage Nipple", "ASTM A53 Gr.B — Hot Dip Galv.", "", "", "MSS SP-95", "NPT", '½"–4"', "(1)(5)"),
  ],
  valves: [
    v("Ball", "VBA10N001N", "Reduced", "—", "600 WOG", "NPT-F", '½"–2"', ""),
    v("Ball", "VBA10N002N", "Full", "—", "600 WOG", "NPT-F", '½"–2"', ""),
  ],
  branch: BRANCH_AG0F,
  notes: [
    "Galvanizado en caliente según ASTM A153.",
    "Si se requiere cañería enterrada, debe recubrirse, y el recubrimiento debe notificarse previamente a Pluspetrol para su aprobación.",
    "Costura recta con 100% de radiografía.",
    "Ver Nota General 1.",
    "El bore debe coincidir con el schedule de la cañería.",
    "Bridas y extremos bridados: cara serrada spiral 125–250 AARH máx.",
    "Tee mecánica con salida de rama roscada NPT, según estándar del fabricante.",
    "Todo el equipamiento, partes y accesorios deben estar listados UL o aprobados FM.",
    "Junta dieléctrica: sólo tipo Pikotek VCS. No se permite tipo Micarta. Incluye manguito aislante, doble aislación y arandelas de acero para tipo Pikotek.",
    "Gaskets, sellos, asientos y empaquetaduras: libres de materiales con asbesto.",
    "Los extremos grooved de la cañería se hacen por deformación plástica (roll grooved).",
    "Espárragos roscados en toda su longitud, con dos tuercas hexagonales semiterminadas pesadas.",
  ],
};

const AG0 = {
  designT: ["-29 a 38", "50", "100", "150"], designP: ["20", "19,6", "18", "16,1"],
  comps: [
    c("Seamless Pipe", "ASTM A53 Gr.B — Hot Dip Galv.", "XS", "", "ASME B36.10M", "NPT", '½"–2"', "(1)"),
    c("", "", "STD", "", "", "NPT", '3"–4"', "(1)"),
    c("Smls Pipe Nipple", "ASTM A53 Gr.B — Hot Dip Galv.", "XS", "", "ASME B36.10M", "NPT", '½"–1½"', "(1)"),
    c("Forged Fittings", "ASTM A105 — Hot Dip Galv.", "", "3000#", "ASME B16.11", "NPT", '½"–4"', "(1)"),
    c("Bushing Reducer Hex.", "ASTM A105 — Hot Dip Galv.", "", "3000#", "ASME B16.11", "NPT", '½"–4"', "(1)"),
    c("Flange", "ASTM A105 — Hot Dip Galv.", "", "150#", "ASME B16.5", "NPT / RF", '½"–4"', "(1)(5)(6)"),
    c("", "", "", "300#", "", "NPT / RF", '2"–4"', "(1)(5)(6)"),
    c("Orifice Flange", "ASTM A105 — Hot Dip Galv.", "", "300#", "ASME B16.5", "NPT / RF", '2"–4"', "(1)(6)(7)"),
    c("Blind Flange", "ASTM A105 — Hot Dip Galv.", "", "150#", "ASME B16.5", "RF", '½"–4"', "(1)(6)"),
    c("Spiral Wound Gaskets", "304 SS Flexible Graphite filler, 4,5mm Nom Thk., 3,2mm Compressed Thk. / CS Zinc outer ring 304 SS inner ring", "", "150#/300#", "ASME B16.20", "—", '½"–4"', "(3)"),
    c("Stud Bolts", "ASTM A-193 Gr.B7-ZINC", "", "", "ASME B18.2.1", "—", "—", "(4)(8)"),
    c("Nuts", "ASTM A-194 Gr.2H-ZINC", "", "", "ASME B18.2.2", "—", "—", ""),
    c("Dielectric Joint", "Ver Nota 9", "", "150#", "ASME B16.21", "RF", '½"–4"', "(9)"),
    c("Spectacle Blind", "ASTM A516 Gr.70", "", "150#", "ASME B16.48", "RF", '1"–4"', ""),
    c("Swage Nipple", "ASTM A53 Gr.B — Hot Dip Galv.", "", "", "MSS SP-95", "NPT", '½"–4"', "(1)(5)"),
  ],
  valves: [
    v("Ball", "RBN8NW0", "Reduced", "—", "800#", "NPT-F", '½"–1½"', ""),
    v("Ball", "FBN8NW0", "Full", "—", "800#", "NPT-F", '½"–1½"', ""),
    v("Ball", "RCC1RW0", "Reduced", "—", "150#", "RF", '2"–4"', ""),
    v("Ball", "FCC1RW0", "Full", "—", "150#", "RF", '2"–4"', ""),
    v("Globe", "GCB8NH0", "—", "—", "800#", "NPT-F", '½"–1½"', ""),
    v("Globe", "GCB1RH0", "—", "—", "150#", "RF", '2"–4"', "Handwheel"),
    v("Check", "CBN8NS0", "—", "Swing", "800#", "NPT-F", '½"–1½"', ""),
    v("Check", "CCB1WD0", "—", "Dual-Plate", "150#", "RF", '2"–4"', ""),
  ],
  branch: BRANCH_A15,
  notes: [
    "Galvanizado en caliente según ASTM A153.",
    "Si se requiere cañería enterrada, debe recubrirse, y el recubrimiento debe notificarse previamente a Pluspetrol para su aprobación.",
    "Gaskets, sellos, asientos y empaquetaduras: libres de materiales con asbesto.",
    "Espárragos roscados en toda su longitud, con dos tuercas hexagonales semiterminadas pesadas.",
    "El bore debe coincidir con el schedule de la cañería.",
    "Bridas y extremos bridados: cara serrada spiral 125–250 AARH máx.",
    "Tap holes: conexión NPTF ½\".",
    "Ver Nota General 2.",
    "Junta dieléctrica: sólo tipo Pikotek VCS. No se permite tipo Micarta. Incluye manguito aislante, doble aislación y arandelas de acero para tipo Pikotek.",
  ],
};

const BC3 = {
  designT: ["-29 a 38", "50", "100", "150", "200"], designP: ["52,1", "51,1", "47,5", "46", "44,7"],
  comps: [
    c("Seamless Pipe", "API 5L Gr.B", "160", "", "ASME B36.10M", "PE", '½"–¾"', ""),
    c("", "", "80", "", "", "PE", '1"–1½"', ""),
    c("", "", "80", "", "", "BE", '2"', "(1)(2)"),
    c("", "", "40", "", "", "BE", '2½"–12"', "(1)(2)"),
    c("SAWL Pipe (100% RX)", "API 5L Gr.B", "40", "", "ASME B36.10M", "BE", '14"–24"', "(1)(2)(3)"),
    c("Seamless Pipe (Nipple)", "ASTM A-106 Gr.B", "XXS", "", "ASME B36.10M", "NPT", '½"–1½"', "(4)"),
    c("Forged Fittings", "ASTM A-105", "", "6000#", "ASME B16.11", "SW", '½"–¾"', ""),
    c("", "", "", "3000#", "", "SW", '1"–1½"', ""),
    c("", "", "", "6000#", "", "NPT", '½"–1½"', "(4)"),
    c("Wrought Pipe Fittings", "ASTM A-234 Gr.WPB", "", "", "ASME B16.9", "BW", '2"–24"', "(6)"),
    c("Flange", "ASTM A-105", "", "300#", "ASME B16.5", "SW / RF", '½"–1½"', "(6)(7)"),
    c("", "", "", "300#", "", "WN / RF", '2"–24"', "(6)(7)"),
    c("Blind Flange", "ASTM A-105", "", "300#", "ASME B16.5", "BLIND RF", '½"–24"', "(7)"),
    c("Orifice Flange", "ASTM A-105", "", "300#", "ASME B16.36", "WN / RF", '2"–24"', "(6)(7)"),
    c("Gaskets", "304 SS Flexible Graphite filler, 4,5mm Nom Thk., 3,2mm Compressed Thk. / CS Zinc outer ring 304 SS inner ring", "", "300#", "ASME B16.20", "—", '½"–24"', "(10)"),
    c("Stud Bolts", "ASTM A-193 Gr.B7-ZINC", "", "", "ASME B18.2.1", "—", "—", "(11)(16)"),
    c("Nuts", "ASTM A-194 Gr.2H-ZINC", "", "", "ASME B18.2.2", "—", "—", ""),
    c("Spectacle Blind", "ASTM A-516 Gr.70", "", "300#", "ASME B16.48", "RF", '1"–12"', ""),
    c("Paddle & Spacer Blind", "ASTM A-516 Gr.70", "", "300#", "", "RF", '14"–24"', ""),
    c("Drip Ring", "ASTM A-516 Gr.70", "", "300#", "", "RF", '1"–12"', "(8)(14)(15)"),
    c("Dielectric Joint", "Ver Nota 9", "", "300#", "ASME B16.21", "RF", '½"–24"', "(9)"),
    c("Olet Fittings", "ASTM A-105", "", "6000#", "MSS SP-97", "SW-NPT", '½"–¾"', ""),
    c("", "", "", "3000#", "", "SW-NPT", '1"–1½"', "(4)(6)"),
    c("", "", "", "3000#", "", "BW", '2"–24"', ""),
    c("Swage Nipple", "ASTM A-234 Gr.WPB", "", "", "MSS SP-95", "BW-PE", '½"–4"', "(6)"),
  ],
  valves: [
    v("Ball", "RCJ8SW0", "Reduced", "—", "800#", "PE", '½"–1½"', "4"),
    v("Ball", "FCJ8SW0", "Full", "—", "800#", "PE", '½"–1½"', "4"),
    v("Ball", "VBA1WC005", "Full", "—", "2000WOG", "NPT-F x PE", '½"–1½"', "3"),
    v("Ball", "RCC3RW0", "Reduced", "—", "300#", "RF", '2"–6"', ""),
    v("Ball", "FCC3RW0", "Full", "—", "300#", "RF", '2"–6"', ""),
    v("Ball", "RCC3RG0", "Reduced", "—", "300#", "RF", '8"–24"', ""),
    v("Ball", "FCC3RG0", "Full", "—", "300#", "RF", '8"–24"', ""),
    v("Gate", "ECB8SH0", "—", "—", "800#", "SW", '½"–1½"', ""),
    v("Gate", "ECB3RH0", "—", "—", "300#", "RF", '2"–8"', "Handwheel"),
    v("Gate", "ECB3RG0", "—", "—", "300#", "RF", '10"–24"', "Gear Box"),
    v("Globe", "GCB8SH0", "—", "—", "800#", "SW", '½"–1½"', ""),
    v("Globe", "GCB3RH0", "—", "—", "300#", "RF", '2"–8"', "HW/Gear Box ≥8\""),
    v("Globe", "GCB3RG0", "—", "—", "300#", "RF", '10"–24"', "Gear Box"),
    v("Butterfly", "BCJ3W00", "—", "Wafer", "300#", "-", '3"–12"', "Operator: By Vendor"),
    v("Butterfly", "BCJ3L00", "—", "Lug", "300#", "-", '14"–24"', "Operator: By Vendor"),
    v("Check", "CCB8SP0", "—", "Piston", "800#", "SW", '½"–1½"', "2"),
    v("Check", "CCB3WD1", "—", "Swing", "300#", "RF", '2"–12"', ""),
    v("Check", "CCB3LD0", "—", "Dual-Plate", "300#", "-", '14"–24"', "Lug Type"),
  ],
  branch: BRANCH_B10A,
  notes: [
    "Extremos biselados según ASME B16.25.",
    "Cañería enterrada: coating externo, a elegir según temperatura de servicio (3LPE fusionado -40 a 85°C, o 3LPP fusionado -20 a 100°C, según NAG 108) — el proveedor debe certificar la temperatura máxima de operación.",
    "Costura recta con 100% de radiografía.",
    "Fittings roscados sobre process piping: sólo para termowells y venteos de prueba hidráulica.",
    "Válvulas de bola socket weld deben quedar en posición abierta al soldarse a la cañería, para no dañar el asiento.",
    "El bore debe coincidir con el schedule de la cañería.",
    "Bridas y extremos bridados: cara serrada spiral 125–250 AARH máx.",
    "Tap hole: ½\" diám. tipo NPT hasta 2\" diám. de cañería, ¾\" para diámetros mayores a 2\".",
    "Junta dieléctrica: sólo tipo Pikotek VCS. No se permite tipo Micarta. Incluye manguito aislante, doble aislación y arandelas de acero para tipo Pikotek.",
    "Gaskets, sellos, asientos y empaquetaduras: libres de materiales con asbesto.",
    "Espárragos roscados en toda su longitud, con dos tuercas hexagonales semiterminadas pesadas.",
    "Ver Nota General 1.",
    "Ver Nota General 7.",
    "Espesor mínimo de drip ring: 38,1 mm.",
    "Oreja de izaje requerida en tamaños 12\" y mayores.",
    "Ver Nota General 2.",
  ],
};

const BC3A = {
  designT: ["-29 a 38", "50", "100", "150", "200"], designP: ["52,1", "51,1", "47,5", "46", "44,7"],
  comps: [
    c("Seamless Pipe", "API 5L Gr.B", "160", "", "ASME B36.10M", "PE", '½"–¾"', ""),
    c("", "", "80", "", "", "PE", '1"–1½"', ""),
    c("", "", "80 (XS)", "", "", "BE", '2"', "(1)(2)"),
    c("", "", "40 (STD)", "", "", "BE", '2½"–12"', "(1)(2)"),
    c("SAWL Pipe (100% RX)", "API 5L Gr.B", "40", "", "ASME B36.10M", "BE", '14"–24"', "(1)(2)(3)"),
    c("Seamless Pipe (Nipple)", "ASTM A-106 Gr.B", "XXS", "", "ASME B36.10M", "NPT", '½"–1½"', "(4)"),
    c("Forged Fittings", "ASTM A-105", "", "6000#", "ASME B16.11", "SW", '½"–¾"', ""),
    c("", "", "", "3000#", "", "SW", '1"–1½"', ""),
    c("", "", "", "6000#", "", "NPT", '½"–1½"', "(4)"),
    c("Wrought Pipe Fittings", "ASTM A-234 Gr.WPB", "", "", "ASME B16.9", "BW", '2"–24"', "(6)"),
    c("Flange", "ASTM A-105", "", "300#", "ASME B16.5", "SW / RF", '½"–1½"', "(6)(7)"),
    c("", "", "", "300#", "", "WN / RF", '2"–24"', "(6)(7)"),
    c("Blind Flange", "ASTM A-105", "", "300#", "ASME B16.5", "BLIND RF", '½"–24"', "(7)"),
    c("Orifice Flange", "ASTM A-105", "", "300#", "ASME B16.36", "WN / RF", '2"–24"', "(6)(7)(14)"),
    c("Gaskets", "304 SS Flexible Graphite filler, 4,5mm Nom Thk., 3,2mm Compressed Thk. / CS Zinc outer ring 304 SS inner ring", "", "300#", "ASME B16.20", "—", '½"–24"', "(11)"),
    c("Stud Bolts", "ASTM A-193 Gr.B7-ZINC", "", "", "ASME B18.2.1", "—", "—", "(12)(17)"),
    c("Nuts", "ASTM A-194 Gr.2H-ZINC", "", "", "ASME B18.2.2", "—", "—", ""),
    c("Spectacle Blind", "ASTM A-516 Gr.70", "", "300#", "ASME B16.48", "RF", '1"–12"', ""),
    c("Paddle & Spacer Blind", "ASTM A-516 Gr.70", "", "300#", "", "RF", '14"–24"', ""),
    c("Drip Ring", "ASTM A-516 Gr.70", "", "300#", "", "RF", '1"–12"', "(8)(15)(16)"),
    c("Dielectric Joint", "Ver Nota 9", "", "300#", "ASME B16.21", "RF", '½"–24"', "(9)"),
    c("Olet Fittings", "ASTM A-105", "", "6000#", "MSS SP-97", "SW-NPT", '½"–¾"', ""),
    c("", "", "", "3000#", "", "SW-NPT", '1"–1½"', "(4)"),
    c("", "", "", "3000#", "", "BW", '2"–24"', ""),
    c("Swage Nipple", "ASTM A-234 Gr.WPB", "", "", "MSS SP-95", "BW-PE", '½"–4"', "(6)"),
  ],
  valves: [
    v("Ball", "VBA08C001", "Full", "—", "2000WOG", "NPT-F x PE", '½"–1½"', "1, 2, 3, 5"),
    v("Ball", "VBA08C002", "Full", "—", "2000WOG", "PE", '½"–1½"', "1, 2, 3, 4"),
    v("Ball", "VBA03C030", "Full", "—", "300#", "RF", '2"–4"', "1, 2, 3"),
    v("Ball", "VBA03C031", "Full", "—", "300#", "RF", '6"–24"', "1, 2, 3"),
    v("Ball", "VBA08C003", "Full", "—", "2000WOG", "NPT-F x PE", '½"–1½"', "1, 2, 3, 5, 6"),
    v("Ball", "VBA08C004", "Full", "—", "2000WOG", "PE", '½"–1½"', "1, 2, 3, 4, 6"),
    v("Gate", "VGA08C009", "—", "—", "800#", "SW", '½"–1½"', ""),
    v("Gate", "VGA03C009", "—", "—", "300#", "RF", '2"–8"', "Handwheel"),
    v("Gate", "VGA03C009", "—", "—", "300#", "RF", '10"–24"', "Gear Box"),
    v("Globe", "VGL08C011", "—", "—", "800#", "SW", '½"–1½"', ""),
    v("Globe", "VGL03C009", "—", "—", "300#", "RF", '2"–6"', "Handwheel"),
    v("Globe", "VGL03C009", "—", "—", "300#", "RF", '8"–24"', "Gear Box"),
    v("Check", "VCK08C001", "—", "Swing", "800#", "SW", '½"–1½"', ""),
    v("Check", "VCK03C011", "—", "Swing", "300#", "RF", '2"–12"', ""),
  ],
  branch: BRANCH_B10A,
  notes: [
    "Extremos biselados según ASME B16.25.",
    "Cañería enterrada: coating externo, a elegir según temperatura de servicio (3LPE fusionado -40 a 85°C, o 3LPP fusionado -20 a 100°C, según NAG 108) — el proveedor debe certificar la temperatura máxima de operación.",
    "Costura recta con 100% de radiografía.",
    "Fittings roscados sobre process piping: sólo para termowells y venteos de prueba hidráulica.",
    "Válvulas de bola socket weld deben quedar en posición abierta al soldarse a la cañería, para no dañar el asiento.",
    "El bore debe coincidir con el schedule de la cañería.",
    "Bridas y extremos bridados: cara serrada spiral 125–250 AARH máx.",
    "Tap hole: ½\" diám. tipo NPT hasta 2\" diám. de cañería, ¾\" para diámetros mayores a 2\".",
    "Junta dieléctrica: sólo tipo Pikotek VCS. No se permite tipo Micarta. Incluye manguito aislante, doble aislación y arandelas de acero para tipo Pikotek.",
    "Válvulas aptas para servicio con arena.",
    "Gaskets, sellos, asientos y empaquetaduras: libres de materiales con asbesto.",
    "Espárragos roscados en toda su longitud, con dos tuercas hexagonales semiterminadas pesadas.",
    "Ver Nota General 1.",
    "Válvulas no aptas para servicios con alta concentración de cloruro.",
    "Espesor mínimo de drip ring: 38,1 mm.",
    "Oreja de izaje requerida en tamaños 12\" y mayores.",
    "Ver Nota General 2.",
    "Extremos SW con niples de extremo plano de 100mm de largo (cada lado).",
    "Extremo 1: NPTF. Extremo 2: SW + niple de extremo plano de 100mm.",
    "Válvulas chicas con tratamiento ENP: sólo para servicios no críticos.",
  ],
};

const CC1 = {
  designT: ["-29 a 38", "50", "100", "150", "200"], designP: ["104,1", "102,2", "95", "92", "89,3"],
  comps: [
    c("Seamless Pipe", "ASTM A106 Gr.B / API 5L Gr.B", "80", "", "", "PE", '½"–1½"', "(2)"),
    c("", "", "XS", "", "ASME B36.10M", "BE", '2"–8"', "(1)(2)"),
    c("", "", "80", "", "", "BE", '10"–12"', "(1)(2)"),
    c("SAWL Pipe (100% RX)", "API 5L Gr.B", "80", "", "ASME B36.10M", "BE", '14"–24"', "(1)(3)(2)"),
    c("Seamless Pipe (Nipple)", "ASTM A106 Gr.B", "160", "", "ASME B36.10M", "PExNPT", '½"–1½"', "(5)(11)"),
    c("Forged Fittings", "ASTM A-105", "", "3000#", "ASME B16.11", "SW", '½"–1½"', "(11)"),
    c("", "", "", "3000#", "", "NPT", '½"–1½"', "(11)"),
    c("Wrought Pipe Fittings", "ASTM A-234 Gr.WPB", "", "", "ASME B16.9", "BW", '2"–24"', "(6)"),
    c("Flange", "ASTM A-105", "", "600#", "ASME B16.5", "SW / RF", '½"–1½"', "(6)(7)"),
    c("", "", "", "600#", "", "WN / RF", '2"–24"', "(6)(7)"),
    c("Blind Flange", "ASTM A-105", "", "600#", "ASME B16.5", "RF", '½"–24"', "(7)"),
    c("Orifice Flange", "ASTM A-105", "", "600#", "ASME B16.36", "WN / RF", '2"–24"', "(6)(7)(13)"),
    c("Spiral Wound Gaskets", "304 SS Flexible Graphite filler, 4,5mm Nom Thk., 3,2mm Compressed Thk. / CS Zinc outer ring 304 SS inner ring", "", "600#", "ASME B16.20", "—", '½"–24"', "(4)"),
    c("Stud Bolts", "ASTM A-193 Gr.B7-ZINC", "", "", "ASME B18.2.1", "—", "—", "(10)(16)"),
    c("Nuts", "ASTM A-194 Gr.2H-ZINC", "", "", "ASME B18.2.2", "—", "—", ""),
    c("Spectacle Blind", "ASTM A-516 Gr.70", "", "600#", "ASME B16.48", "RF", '1"–12"', ""),
    c("Paddle & Spacer Blind", "ASTM A-516 Gr.70", "", "600#", "", "RF", '14"–24"', ""),
    c("Drip Ring", "ASTM A-516 Gr.70", "", "600#", "", "RF", '1"–12"', "(8)(14)(15)"),
    c("Dielectric Joint", "Ver Nota 9", "", "600#", "ASME B16.21", "RF", '½"–24"', "(9)"),
    c("Olet Fittings", "ASTM A-105", "", "6000#", "MSS SP-97", "NPT", '½"–1½"', "(5)(6)(11)"),
    c("", "", "", "3000#", "", "SW / BW", '½"–24"', "(5)(6)(11)"),
    c("Swage Nipple", "ASTM A234 WPB", "", "", "MSS SP-95", "BW-PE", '½"–4"', "(6)"),
  ],
  valves: [
    v("Ball", "RCJ8SW0", "Reduced", "—", "800#", "PE", '½"–1½"', ""),
    v("Ball", "FCJ8SW0", "Full", "—", "800#", "PE", '½"–1½"', ""),
    v("Ball", "VBA1WC005", "Full", "—", "2000WOG", "NPT-F x PE", '½"–1½"', ""),
    v("Ball", "VBA06C019", "Reduced", "—", "600#", "RF", '2"–24"', ""),
    v("Ball", "VBA06C020", "Full", "—", "600#", "RF", '2"–24"', ""),
    v("Gate", "VGA08C007", "—", "—", "800#", "SW", '½"–1½"', ""),
    v("Gate", "VGA06C004", "—", "—", "600#", "RF", '2"–24"', "HW/Gear box ≥8\""),
    v("Globe", "VGL08C004", "—", "—", "800#", "SW", '½"–1½"', ""),
    v("Globe", "VGL06C006", "—", "—", "600#", "RF", '2"–24"', "HW/Gear box ≥6\""),
    v("Check", "VCP08C001", "—", "Piston", "800#", "SW", '½"–1½"', "2"),
    v("Check", "VCK06C008", "—", "Swing", "600#", "RF", '2"–12"', ""),
    v("Check", "VCK06C007", "—", "Dual-Plate", "600#", "-", '14"–24"', "Wafer Type"),
    v("Butterfly", "VBY06C002", "—", "Wafer/Lug", "600#", "-", '3"–24"', "Gear Box"),
  ],
  branch: BRANCH_B10A,
  notes: [
    "Extremos biselados según ASME B16.25.",
    "Cañería enterrada: coating externo, a elegir según temperatura de servicio (3LPE fusionado -40 a 85°C, o 3LPP fusionado -20 a 100°C, según NAG 108) — el proveedor debe certificar la temperatura máxima de operación.",
    "Costura recta con 100% de radiografía.",
    "Gaskets, sellos, asientos y empaquetaduras: libres de materiales con asbesto.",
    "NPT según ASME B1.20.1.",
    "El bore debe coincidir con el schedule de la cañería.",
    "Bridas y extremos bridados: cara serrada spiral 125–250 AARH máx.",
    "Tap hole: ½\" diám. tipo NPT hasta 2\" diám. de cañería, ¾\" para diámetros mayores a 2\".",
    "Junta dieléctrica: sólo tipo Pikotek VCS. No se permite tipo Micarta. Incluye manguito aislante, doble aislación y arandelas de acero para tipo Pikotek.",
    "Espárragos roscados en toda su longitud, con dos tuercas hexagonales semiterminadas pesadas.",
    "Fittings roscados sobre process piping: sólo para termowells y venteos de prueba hidráulica.",
    "Ver Nota General 1.",
    "Ver Nota General 7.",
    "Espesor mínimo de drip ring: 38,1 mm.",
    "Oreja de izaje requerida en tamaños 12\" y mayores.",
    "Ver Nota General 2.",
  ],
};

const DC1 = {
  designT: ["-29 a 65", "100", "150", "200"], designP: ["150", "142,6", "137,9", "134"],
  comps: [
    c("Seamless Pipe", "ASTM A106 Gr.B / API 5L Gr.B", "80", "", "ASME B36.10M", "PE", '½"–1½"', ""),
    c("", "", "XS", "", "", "BE", '2"–3"', "(1)(2)"),
    c("", "", "120", "", "", "BE", '4"–12"', ""),
    c("SAWL Pipe (100% RX)", "API 5L Gr.B", "100", "", "ASME B36.10M", "BE", '14"–24"', "(1)(2)(3)"),
    c("Seamless Pipe (Nipple)", "ASTM A106 Gr.B", "160", "", "ASME B36.10M", "PExNPT", '½"–1½"', "(5)(11)"),
    c("Forged Fittings", "ASTM A-105", "", "3000#", "ASME B16.11", "SW", '½"–1½"', ""),
    c("", "", "", "3000#", "", "NPT", '½"–1½"', "(11)"),
    c("Wrought Pipe Fittings", "ASTM A-234 Gr.WPB", "", "", "ASME B16.9", "BW", '2"–24"', "(6)"),
    c("Flange", "ASTM A-105", "", "1500#", "ASME B16.5", "SW / RJ", '½"–1½"', ""),
    c("", "", "", "1500#", "", "WN / RJ", '2"', "(6)(7)"),
    c("", "", "", "900#", "", "WN / RJ", '3"–24"', ""),
    c("Blind Flange", "ASTM A-105", "", "1500#", "ASME B16.5", "BLIND RJ", '½"–2"', "(6)(7)"),
    c("", "", "", "900#", "", "BLIND RJ", '3"–24"', ""),
    c("Orifice Flange", "ASTM A-105", "", "900#", "ASME B16.36", "WN / RJ", '1"–24"', "(4)(6)(7)"),
    c("Gaskets", "Octagonal Ring Joint, Soft Iron", "", "1500#", "ASME B16.20", "—", '½"–2"', ""),
    c("", "", "", "900#", "", "—", '3"–24"', ""),
    c("Stud Bolts", "ASTM A-193 Gr.B7-ZINC", "", "", "ASME B18.2.1", "—", "—", "(10)(17)"),
    c("Nuts", "ASTM A-194 Gr.2H-ZINC", "", "", "ASME B18.2.2", "—", "—", ""),
    c("Spectacle Blind", "ASTM A-516 Gr.70", "", "1500#", "ASME B16.48", "RJ", '1"–2"', "(15)"),
    c("", "", "", "900#", "", "RJ", '3"–4"', "(15)"),
    c("Paddle & Spacer Blind", "ASTM A-516 Gr.70", "", "900#", "", "RJ", '6"–24"', "(15)"),
    c("Drip Ring", "ASTM A-516 Gr.70", "", "1500#", "ASME B16.48", "RJ", '1"–2"', "(8)(12)(14)"),
    c("", "", "", "900#", "", "RJ", '3"–24"', "(8)(12)(14)"),
    c("Dielectric Joint", "Ver Nota 9", "", "1500#", "ASME B16.21", "RJ", '½"–2"', "(9)"),
    c("", "", "", "900#", "", "RJ", '3"–24"', "(9)"),
    c("Olet Fittings", "ASTM A-105", "", "", "MSS SP-97", "BW-SW-NPT", '½"–24"', "(5)(6)(11)(13)"),
    c("Swage Nipple", "ASTM A234 WPB", "", "", "MSS SP-95", "BW-PE", '½"–4"', "(5)(6)(11)"),
  ],
  valves: [
    v("Ball", "RCJ7SW0", "Reduced", "—", "1500#", "PE", '½"–1½"', "2"),
    v("Ball", "FCJ7SW0", "Full", "—", "1500#", "PE", '½"–1½"', "2"),
    v("Ball", "FCJ7SW1", "Full", "—", "1500#", "NPT-F x PE", '½"–1½"', "4"),
    v("Ball", "RCC9JW0", "Reduced", "—", "900# / 1500#", "RJ", '2"–4"', ""),
    v("Ball", "FCC9JW0", "Full", "—", "900# / 1500#", "RJ", '2"–4"', ""),
    v("Ball", "RCC9JG0", "Reduced", "—", "900#", "RJ", '6"–24"', ""),
    v("Ball", "FCC9JG0", "Full", "—", "900#", "RJ", '6"–24"', ""),
    v("Gate", "VGA15C001", "—", "—", "1500#", "SW", '½"–1½"', ""),
    v("Gate", "ECB9JH0", "—", "—", "900# / 1500#", "RJ", '2"–4"', "Handwheel"),
    v("Gate", "VGA09C008", "—", "—", "900#", "RJ", '6"–24"', "Gear Box"),
    v("Globe", "GCB7SH0", "—", "—", "1500#", "SW", '½"–1½"', ""),
    v("Globe", "GCB9JH0", "—", "—", "900# / 1500#", "RJ", '2"–4"', "HW/Gear Box ≥4\""),
    v("Globe", "GCB9JG0", "—", "—", "900#", "RJ", '6"–24"', "Gear Box"),
    v("Check", "CCB7SP0", "—", "Piston", "1500#", "SW", '½"–1½"', "3"),
    v("Check", "CCB9ED1", "—", "Swing", "900# / 1500#", "RJ", '2"–12"', ""),
    v("Check", "CCB9ED0", "—", "Dual-Plate", "900#", "-", '14"–24"', "Lug Type"),
  ],
  branch: BRANCH_B10A,
  notes: [
    "Extremos biselados según ASME B16.25.",
    "Cañería enterrada: coating externo, a elegir según temperatura de servicio (3LPE fusionado -40 a 85°C, o 3LPP fusionado -20 a 100°C, según NAG 108) — el proveedor debe certificar la temperatura máxima de operación.",
    "Costura recta con 100% de radiografía.",
    "Ver Nota General 7.",
    "NPT según ASME B1.20.1.",
    "El bore debe coincidir con el schedule de la cañería.",
    "Bridas y extremos bridados: acabado liso, ranura 63 AARH máx.",
    "Tap hole: ½\" diám. hasta 2\" diám. de cañería, ¾\" para diámetros mayores — tipo socket weld.",
    "Junta dieléctrica: sólo tipo Pikotek VCS. No se permite tipo Micarta. Incluye manguito aislante, doble aislación y arandelas de acero para tipo Pikotek.",
    "Espárragos roscados en toda su longitud, con dos tuercas hexagonales semiterminadas pesadas.",
    "Fittings roscados sobre process piping: sólo para termowells y venteos de prueba hidráulica.",
    "Espesor mínimo de drip ring: 38,1 mm.",
    "Ver Nota General 8.",
    "Oreja de izaje requerida en tamaños 12\" y mayores.",
    "Para spectacle blinds y espaciadores, en diámetros mayores a 2\" se debe proveer jack screws según GRAL-100-ET-C-100.",
    "Ver Nota General 1.",
    "Ver Nota General 2.",
  ],
};

const AF0G = {
  designT: ["0 a 80"], designP: ["10,5"],
  comps: [
    c("Pipe", "GRP, Vinylester Resin", "", "", "ASTM D2996 / ASTM D2310", "PE", '1"–16"', "(1)(7)"),
    c("Fittings", "GRP, Vinylester Resin", "", "", "ASTM D5685", "PE", '1"–16"', "(1)(2)(5)(7)"),
    c("Flange", "Integral GRP, Vinylester Resin", "", "150#", "ASTM D5685 / ASME B16.5", "PE / FF", '1"–16"', "(6)(9)(10)"),
    c("Blind Flange", "GRP, Vinylester Resin", "", "150#", "ASTM D5685 / ASME B16.5", "PE / FF", '1"–16"', "(6)(10)(13)"),
    c("Gasket", "Full face type, expanded PTFE, e=3,2mm", "", "150#", "ASME B16.21", "—", '1"–16"', ""),
    c("Stud Bolts", "ASTM A-193 Gr.B7-ZINC", "", "", "ASME B18.2.1", "—", "—", "(11)(12)(16)"),
    c("Nuts", "ASTM A-194 Gr.2H-ZINC", "", "", "ASME B18.2.2", "—", "—", ""),
    c("Spectacle Blind", "ASTM A105, PTFE lined", "", "150#", "ASME B16.48", "FF", '1"–12"', ""),
    c("Paddle & Spacer Blind", "ASTM A105, PTFE lined", "", "150#", "ASME B16.48", "FF", '14"–16"', ""),
  ],
  valves: [
    v("Ball", "VBA01C028", "Reduced", "—", "150#", "FF", '2"–6"', "3, 5"),
    v("Ball", "VBA01C029", "Reduced", "—", "150#", "FF", '8"–16"', ""),
    v("Gate", "VGA01C011", "—", "—", "150#", "FF", '2"–16"', "4, 5 HW/Gear box ≥12\""),
    v("Globe", "VGL01C011", "—", "—", "150#", "FF", '2"–10"', "3, 4, 5 HW/Gear box ≥8\""),
    v("Butterfly", "VBY01C010", "—", "Lug", "150#", "FF", '3"–12"', "2, 5 HW/Gear box ≥8\""),
    v("Check", "VCK01C014", "—", "Swing", "150#", "FF", '2"–16"', "3, 4, 5"),
  ],
  branch: BRANCH_PRFV1,
  notes: [
    "El fabricante debe especificar el espesor de pared adecuado para la clase de presión, según ASTM D2996/D2310. Diámetro externo, interno y espesor deben ser provistos por el fabricante para revisión y aprobación — incluye barrera de corrosión interna de 3mm (2 capas de velo Nexus, resina vinil éster tipo A bisfenólico), refuerzo estructural por bobinado filamentario tipo E, y barrera externa protegida contra UV.",
    "Refuerzo estructural de fittings: mat de fibra de vidrio tipo E 450 g/m² con velos de roving bidireccional — 220 g/m² hasta 4\", 600 g/m² por encima de 4\".",
    "No se permite ningún material de relleno adicional en cañería, fittings o bridas de GRP (ej. arena o material reciclado).",
    "Examen visual según ASTM D2563-94 (clasificación de defectos visuales en laminados de plástico reforzado con vidrio).",
    "Fittings fabricados por método hand lay-up según recomendaciones de NBS-PS-15/69.",
    "Bridas según ASME B16.5 Clase 150. Al fabricar, evitar desgarros y delaminación del material.",
    "Sistema de unión según ASME RTP-1 2011 y prácticas particulares para químicos altamente corrosivos. No se permiten fillers (fuera de los indicados) para el sellado de biseles. Unión 100% envuelta. Biseles ≤18° para permitir aplicación de velos y fibra de vidrio.",
    "Longitud de unión: 100mm para fittings hasta 3\"; al menos un diámetro para fittings de 4\" y mayores.",
    "Conexiones bridadas: cuidado especial con el torque — valores provistos por el fabricante.",
    "Cara serrada espiral o concéntrica, 125-250 μin Ra según MSS SP-06.",
    "Longitud según ASME B16.5 (excepto PSV, placa orificio, drip ring, válvulas tipo wafer).",
    "Usar arandelas de acero inoxidable 316 en ambos extremos de los espárragos.",
    "Fittings de cañería según ASTM D5685.",
    "El proveedor de GRP debe proporcionar el procedimiento de envoltura para cañería y fittings.",
    "Los soportes de cañería deben ser diseñados por el proveedor de GRP; el arreglo, tipo (deslizante, guiado, restricción, abrazadera de punto fijo, etc.), distancia entre soportes y posición serán recomendados por el proveedor.",
    "Ver Nota General 2.",
    "Conexiones de instrumentos: se hacen con bridas derivadas de la cañería principal (diámetro mínimo de brida 1\"); para conectar el instrumento hay que convertir de GRP a metal — todas las piezas metálicas deben ser clase BS0M. Lo mismo aplica a conexiones de venteos y drenajes.",
  ],
};

const AC1R = {
  designT: ["-20 a 38", "65", "90"], designP: ["20", "18,71", "18,3"],
  comps: [
    c("Seamless Pipe", "ASTM A106 Gr.B", "40", "", "ASME B36.10M", "BE", '2"–6"', "(1)(2)(4)"),
    c("", "", "20", "", "", "BE", '8"–12"', "(1)(2)(4)"),
    c("SAWL Pipe (100% RX)", "API 5L Gr.B", "10", "", "ASME B36.10M", "BE", '14"–18"', "(1)(2)(3)"),
    c("", "", "20", "", "", "BE", '20"–24"', "(1)(2)(3)"),
    c("Wrought Pipe Fittings", "ASTM A-234 Gr.WPB", "", "", "ASME B16.9", "BW", '2"–24"', "(6)(4)"),
    c("Flange", "ASTM A-105", "", "150#", "ASME B16.5", "WN / RF", '2"–24"', "(6)(7)(4)"),
    c("Blind Flange", "ASTM A-105", "", "150#", "ASME B16.5", "RF", '2"–24"', "(7)(18)"),
    c("Blind Flange", "ASTM A-182 F60", "", "150#", "ASME B16.5", "RF", '2"', "(7)"),
    c("Orifice Flange", "ASTM A-105", "", "300#", "ASME B16.36", "WN / RF", '2"–24"', "(6)(7)"),
    c("Spiral Wound Gaskets", "304 SS Flexible Graphite filler, 4,5mm Nom Thk., 3,2mm Compressed Thk. / CS Zinc outer ring 304 SS inner ring", "", "150#/300#", "ASME B16.20", "—", '2"–24"', "(11)"),
    c("Stud Bolts", "ASTM A-193 Gr.B7-ZINC", "", "", "ASME B18.2.1", "—", "—", "(12)(17)"),
    c("Nuts", "ASTM A-194 Gr.2H-ZINC", "", "", "ASME B18.2.2", "—", "—", ""),
    c("Spectacle Blind", "ASTM A-516 Gr.70 ZINC", "", "150#", "ASME B16.48", "RF", '2"–12"', ""),
    c("Paddle & Spacer Blind", "ASTM A-516 Gr.70 ZINC", "", "150#", "ASME B16.48", "RF", '14"–24"', ""),
    c("Dielectric Joint", "Ver Nota 9", "", "150#", "ASME B16.21", "RF", '2"–24"', "(9)"),
    c("Weldolet", "ASTM A-105", "", "", "MSS SP-97", "BW", '2"–24"', "(6)"),
  ],
  valves: [
    v("Ball", "VBA01C022", "Reduced", "—", "150#", "RF", '2"–6"', "2, 3"),
    v("Ball", "VBA01C026", "Full", "—", "150#", "RF", '2"–6"', "2, 3"),
    v("Ball", "VBA01C023", "Reduced", "—", "150#", "RF", '8"–24"', "2, 3"),
    v("Ball", "VBA01C027", "Full", "—", "150#", "RF", '8"–24"', "2, 3"),
    v("Gate", "VGA01C010", "—", "—", "150#", "RF", '2"–24"', "2, 3, HW/Gear box ≥12\""),
    v("Globe", "VGL01C010", "—", "—", "150#", "RF", '2"–10"', "2, 3, HW/Gear box ≥8\""),
    v("Check", "VCK01C013", "—", "Swing", "150#", "RF", '2"–24"', "2, 3"),
  ],
  branch: BRANCH_2A24,
  notes: [
    "Extremos biselados según ASME B16.25.",
    "Cañería enterrada: coating externo, a elegir según temperatura de servicio (3LPE fusionado -40 a 85°C, o 3LPP fusionado -20 a 100°C, según NAG 108) — el proveedor debe certificar la temperatura máxima de operación.",
    "Costura recta con 100% de radiografía.",
    "Para cañerías, fittings y válvulas de diámetros menores a 2\", ver clase BS0M.",
    "NPT según ASME B1.20.1.",
    "El bore debe coincidir con el schedule de la cañería.",
    "Bridas y extremos bridados: cara serrada spiral 125–250 AARH máx.",
    "Ver Nota General 1.",
    "Junta dieléctrica: sólo tipo Pikotek VCS. No se permite tipo Micarta. Incluye manguito aislante, doble aislación y arandelas de acero para tipo Pikotek.",
    "Toda soldadura de cañería mayor a 1¼\" (31,75mm) debe relevarse de tensiones según procedimiento de soldadura aplicable (antes del procedimiento de recubrimiento interno).",
    "Gaskets, sellos, asientos y empaquetaduras: libres de materiales con asbesto.",
    "Espárragos roscados en toda su longitud, con dos tuercas hexagonales semiterminadas pesadas.",
    "Todos los spools deben tener extremos bridados para garantizar cobertura interior con el coating seleccionado.",
    "El diámetro mínimo a pintar internamente es 2\".",
    "Para esta clase AC1R la temperatura máxima se considera 90°C, por requisitos térmicos del coating interno de cañería. El proveedor debe certificar la temperatura máxima de operación de sus productos.",
    "El coating interno de cañería debe ser ZAP-10 de ZOXI o producto de igual calidad — a proponer a Pluspetrol para su aprobación.",
    "Ver Nota General 2.",
    "Bridas ciegas deben tener coating interno epoxi.",
  ],
};

const BC1R = {
  designT: ["-20 a 38", "65", "90"], designP: ["52,1", "50,02", "48,2"],
  comps: [
    c("Seamless Pipe", "ASTM A106 Gr.B", "40", "", "ASME B36.10M", "BE", '2"–6"', "(1)(2)(4)"),
    c("", "", "30", "", "", "BE", '8"–10"', "(1)(2)(4)"),
    c("", "", "STD", "", "", "BE", '12"', "(1)(2)(4)"),
    c("SAWL Pipe (100% RX)", "API 5L Gr.B", "30", "", "ASME B36.10M", "BE", '14"', "(1)(2)"),
    c("", "", "40", "", "", "BE", '16"–18"', "(1)(2)"),
    c("", "", "30", "", "", "BE", '20"', "(1)(2)"),
    c("", "", "40", "", "", "BE", '24"', "(1)(2)"),
    c("Wrought Pipe Fittings", "ASTM A-234 Gr.WPB", "", "", "ASME B16.9", "BW", '2"–24"', "(6)(4)"),
    c("Flange", "ASTM A-105", "", "300#", "ASME B16.5", "WN RF", '2"–24"', "(6)(7)(4)"),
    c("Blind Flange", "ASTM A-105", "", "300#", "ASME B16.5", "RF", '2"–24"', "(7)(17)"),
    c("Blind Flange", "ASTM A-182 F60", "", "300#", "ASME B16.5", "RF", '2"', "(7)"),
    c("Orifice Flange", "ASTM A-105", "", "300#", "ASME B16.36", "WN / RF", '2"–24"', "(6)(7)"),
    c("Gaskets", "304 SS Flexible Graphite filler, 4,5mm Nom Thk., 3,2mm Compressed Thk. / CS Zinc outer ring 304 SS inner ring", "", "300#", "ASME B16.20", "—", '2"–24"', "(11)"),
    c("Stud Bolts", "ASTM A-193 Gr.B7-ZINC", "", "", "ASME B18.2.1", "—", "—", "(5)(12)"),
    c("Nuts", "ASTM A-194 Gr.2H-ZINC", "", "", "ASME B18.2.2", "—", "—", ""),
    c("Spectacle Blind", "ASTM A-516 Gr.70 ZINC", "", "300#", "ASME B16.48", "RF", '2"–12"', ""),
    c("Paddle & Spacer Blind", "ASTM A-516 Gr.70 ZINC", "", "300#", "ASME B16.48", "RF", '14"–24"', ""),
    c("Dielectric Joint", "Ver Nota 9", "", "300#", "ASME B16.21", "RF", '2"–24"', "(9)"),
    c("Olet Fittings", "ASTM A-105", "", "3000#", "MSS SP-97", "BW", '2"–24"', "(6)"),
  ],
  valves: [
    v("Ball", "VBA03C022", "Reduced", "—", "300#", "RF", '2"–6"', "2, 4"),
    v("Ball", "VBA03C028", "Full", "—", "300#", "RF", '2"–6"', "2, 4"),
    v("Ball", "VBA03C023", "Reduced", "—", "300#", "RF", '8"–24"', "2, 4"),
    v("Ball", "VBA03C029", "Full", "—", "300#", "RF", '8"–24"', "2, 4"),
    v("Gate", "VGA03C009", "—", "—", "300#", "RF", '2"–24"', "2, 4, HW/Gear box ≥10\""),
    v("Globe", "VGL03C009", "—", "—", "300#", "RF", '2"–24"', "2, 4, HW/Gear box ≥8\""),
    v("Check", "VCK03C011", "—", "Swing", "300#", "RF", '2"–24"', "3, 4"),
  ],
  branch: BRANCH_2A24,
  notes: [
    "Extremos biselados según ASME B16.25.",
    "Cañería enterrada: coating externo, a elegir según temperatura de servicio (3LPE fusionado -40 a 85°C, o 3LPP fusionado -20 a 100°C, según NAG 108) — el proveedor debe certificar la temperatura máxima de operación.",
    "Costura recta con 100% de radiografía.",
    "Para cañerías, fittings y válvulas de diámetros menores a 2\", ver clase CS0M.",
    "Ver Nota General 2.",
    "El bore debe coincidir con el schedule de la cañería.",
    "Bridas y extremos bridados: cara serrada spiral 125–250 AARH máx.",
    "Ver Nota General 1.",
    "Junta dieléctrica: sólo tipo Pikotek VCS. No se permite tipo Micarta. Incluye manguito aislante, doble aislación y arandelas de acero para tipo Pikotek.",
    "Toda soldadura de cañería mayor a 1¼\" (31,75mm) debe relevarse de tensiones según procedimiento de soldadura aplicable (antes del procedimiento de recubrimiento interno).",
    "Gaskets, sellos, asientos y empaquetaduras: libres de materiales con asbesto.",
    "Espárragos roscados en toda su longitud, con dos tuercas hexagonales semiterminadas pesadas.",
    "Todos los spools deben tener extremos bridados para garantizar cobertura interior con el coating seleccionado.",
    "El diámetro mínimo a pintar internamente es 2\".",
    "Para esta clase BC1R la temperatura máxima se considera 90°C, por requisitos térmicos del coating interno de cañería. El proveedor debe certificar la temperatura máxima de operación de sus productos.",
    "El coating interno de cañería debe ser ZAP-10 de ZOXI o producto de igual calidad — a proponer a Pluspetrol para su aprobación.",
    "Bridas ciegas deben tener coating interno epoxi.",
  ],
};

const DC1R = {
  designT: ["-20 a 38", "50", "90"], designP: ["156,2", "153,4", "144,8"],
  comps: [
    c("Seamless Pipe", "API 5L Gr.B", "80", "", "ASME B36.10M", "BE", '2"–3"', "(1)(2)(4)"),
    c("", "", "120", "", "", "BE", '4"–12"', "(1)(2)(4)"),
    c("SAWL Pipe (100% RX)", "API 5L Gr.B", "100", "", "ASME B36.10M", "BE", '14"', "(1)(2)"),
    c("", "", "120", "", "", "BE", '16"–20"', "(1)(2)"),
    c("", "", "100", "", "", "BE", '24"', "(1)(2)"),
    c("Wrought Pipe Fittings", "ASTM A-234 Gr.WPB", "", "", "ASME B16.9", "BW", '2"–24"', "(6)(4)"),
    c("Flange", "ASTM A-105", "", "1500#", "ASME B16.5", "WN / RJ", '2"', "(6)(7)(4)"),
    c("", "", "", "900#", "", "WN / RJ", '3"–24"', "(6)(7)(4)"),
    c("Blind Flange", "ASTM A-105", "", "1500#", "ASME B16.5", "BLIND RJ", '2"', "(7)(19)"),
    c("", "", "", "900#", "", "BLIND RJ", '3"–24"', "(7)(19)"),
    c("Blind Flange", "ASTM A182 F316L", "", "1500#", "ASME B16.5", "BLIND RJ", '2"', "(7)"),
    c("Orifice Flange", "ASTM A-105", "", "1500#", "ASME B16.36", "WN / RJ", '2"', "(6)(7)"),
    c("", "", "", "900#", "", "WN / RJ", '3"–24"', "(6)(7)"),
    c("Gaskets", "Octagonal Ring Joint, Soft Iron", "", "1500#", "ASME B16.20", "—", '2"', "(12)"),
    c("", "", "", "900#", "", "—", '3"–24"', "(12)"),
    c("Stud Bolts", "ASTM A-193 Gr.B7-ZINC", "", "", "ASME B18.2.1", "—", "—", "(5)(13)"),
    c("Nuts", "ASTM A-194 Gr.2H-ZINC", "", "", "ASME B18.2.2", "—", "—", ""),
    c("Spectacle Blind", "ASTM A-516 Gr.70 ZINC", "", "1500#", "ASME B16.48", "RJ", '2"', ""),
    c("", "", "", "900#", "", "RJ", '3"–4"', ""),
    c("Paddle & Spacer Blind", "ASTM A-516 Gr.70 ZINC", "", "900#", "", "RJ", '6"–24"', ""),
    c("Dielectric Joint", "Ver Nota 9", "", "1500#", "ASME B16.21", "—", '2"', "(9)"),
    c("", "", "", "900#", "", "—", '3"–24"', "(9)"),
    c("Olet Fittings", "ASTM A-105", "", "", "MSS SP-97", "BW", '2"–24"', "(6)(22)"),
  ],
  valves: [
    v("Ball", "RCC9JW1", "Reduced", "—", "900# / 1500#", "RJ", '2"–24"', "2, 3"),
    v("Ball", "FCC9JW1", "Full", "—", "900# / 1500#", "RJ", '2"–24"', "2, 3"),
    v("Gate", "VGA09C009", "—", "—", "900# / 1500#", "RJ", '2"–24"', "2, 3, HW/Gear box ≥6\""),
    v("Globe", "VGL09C009", "—", "—", "900# / 1500#", "RJ", '2"–24"', "2, 3, HW/Gear box ≥4\""),
    v("Check", "VCK09C010", "—", "Swing", "900# / 1500#", "RJ", '2"–24"', "2, 3"),
  ],
  branch: BRANCH_2A24,
  notes: [
    "Extremos biselados según ASME B16.25.",
    "Cañería enterrada: coating externo, a elegir según temperatura de servicio (3LPE fusionado -40 a 85°C, o 3LPP fusionado -20 a 100°C, según NAG 108) — el proveedor debe certificar la temperatura máxima de operación.",
    "Costura recta con 100% de radiografía.",
    "Para cañerías, fittings y válvulas de diámetros menores a 2\", ver clase ES0M.",
    "Ver Nota General 2.",
    "El bore debe coincidir con el schedule de la cañería.",
    "Bridas y extremos bridados: acabado liso, ranura 63 AARH máx.",
    "Ver Nota General 1.",
    "Junta dieléctrica: sólo tipo Pikotek VCS. No se permite tipo Micarta. Incluye manguito aislante, doble aislación y arandelas de acero para tipo Pikotek.",
    "Toda soldadura de cañería mayor a 1¼\" (31,75mm) debe relevarse de tensiones según procedimiento de soldadura aplicable.",
    "Gaskets, sellos, asientos y empaquetaduras: libres de materiales con asbesto.",
    "Espárragos roscados en toda su longitud, con dos tuercas hexagonales semiterminadas pesadas.",
    "Todos los spools deben tener extremos bridados para garantizar cobertura interior con el coating seleccionado.",
    "El diámetro mínimo a pintar internamente es 2\".",
    "Para esta clase DC1R la temperatura máxima se considera 90°C, por requisitos térmicos del coating interno de cañería. El proveedor debe certificar la temperatura máxima de operación de sus productos.",
    "El coating interno de cañería debe ser ZAP-10 de ZOXI o producto de igual calidad — a proponer a Pluspetrol para su aprobación.",
    "Bridas ciegas deben tener coating interno epoxi.",
    "El schedule del weldolet debe igualar el schedule de la cañería de la rama.",
  ],
};

const EC1R = {
  designT: ["-20 a 38", "50", "90"], designP: ["210,8", "204", "182,7"],
  comps: [
    c("Seamless Pipe", "API 5L Gr.B", "160", "", "ASME B36.10M", "BE", '2"–12"', "(1)(2)(18)"),
    c("SAWL Pipe (100% RX)", "API 5L Gr.B", "160", "", "ASME B36.10M", "BE", '14"–24"', "(1)(2)(3)"),
    c("Wrought Pipe Fittings", "ASTM A-234 Gr.WPB", "", "", "ASME B16.9", "BW", '2"–24"', "(4)(18)"),
    c("Flange", "ASTM A-105", "", "1500#", "ASME B16.5", "WN / RJ", '2"–24"', "(4)(5)(18)"),
    c("Blind Flange", "ASTM A-105", "", "1500#", "ASME B16.5", "BLIND RJ", '2"–24"', "(5)(15)"),
    c("Blind Flange", "ASTM A182 F316L", "", "1500#", "ASME B16.5", "BLIND RJ", '2"', "(5)"),
    c("Orifice Flange", "ASTM A-105", "", "1500#", "ASME B16.36", "WN / RJ", '2"–24"', "(6)(7)"),
    c("Gaskets", "Octagonal Ring Joint, Soft Iron", "", "1500#", "ASME B16.20", "—", '2"–24"', "(8)"),
    c("Stud Bolts", "ASTM A-193 Gr.B7-ZINC", "", "", "ASME B18.2.1", "—", "—", "(9)(10)"),
    c("Nuts", "ASTM A-194 Gr.2H-ZINC", "", "", "ASME B18.2.2", "—", "—", ""),
    c("Spectacle Blind", "ASTM A-516 Gr.70 ZINC", "", "1500#", "ASME B16.48", "RJ", '2"–4"', ""),
    c("Paddle & Spacer Blind", "ASTM A-516 Gr.70 ZINC", "", "1500#", "", "RJ", '6"–24"', ""),
    c("Dielectric Joint", "Servicio muy crítico", "", "1500#", "ASME B16.21", "—", '2"–24"', "(6)"),
    c("Olet Fittings", "ASTM A-105", "", "", "MSS SP-97", "BW", '2"–24"', "(4)"),
  ],
  valves: [
    v("Ball", "VBA15C001", "Full", "—", "1500#", "RJ", '2"–24"', "2, 3"),
    v("Ball", "VBA15C002", "Reduced", "—", "1500#", "RJ", '2"–24"', "2, 3"),
    v("Gate", "VGA15C002", "—", "—", "1500#", "RJ", '2"–24"', "2, 3, HW/Gear box ≥4\""),
    v("Globe", "VGL15C001", "—", "—", "1500#", "RJ", '2"–24"', "2, 3, HW/Gear box ≥4\""),
    v("Check", "VCK15C001", "—", "Swing", "1500#", "RJ", '2"–24"', "2, 3"),
  ],
  branch: BRANCH_2A24,
  notes: [
    "Extremos biselados según ASME B16.25.",
    "Cañería enterrada: coating externo, a elegir según temperatura de servicio (3LPE fusionado -40 a 85°C, o 3LPP fusionado -20 a 100°C, según NAG 108) — el proveedor debe certificar la temperatura máxima de operación.",
    "Costura recta con 100% de radiografía.",
    "El bore debe coincidir con el schedule de la cañería.",
    "Bridas y extremos bridados: acabado liso, ranura 63 AARH máx.",
    "Junta dieléctrica: sólo tipo Pikotek VCS. No se permite tipo Micarta. Incluye manguito aislante, doble aislación y arandelas de acero para tipo Pikotek.",
    "Toda soldadura de cañería mayor a 1¼\" (31,75mm) debe relevarse de tensiones según procedimiento de soldadura aplicable.",
    "Gaskets, sellos, asientos y empaquetaduras: libres de materiales con asbesto.",
    "Espárragos roscados en toda su longitud, con dos tuercas hexagonales semiterminadas pesadas.",
    "Ver Nota General 2.",
    "Todos los spools deben tener extremos bridados para garantizar cobertura interior con el coating seleccionado.",
    "El diámetro mínimo a pintar internamente es 2\".",
    "Para esta clase EC1R la temperatura máxima se considera 90°C, por requisitos térmicos del coating interno de cañería. El proveedor debe certificar la temperatura máxima de operación de sus productos.",
    "El coating interno de cañería debe ser ZAP-10 de ZOXI o producto de igual calidad — a proponer a Pluspetrol para su aprobación.",
    "Bridas ciegas deben tener coating interno epoxi.",
    "Ver Nota General 1.",
    "Para cañerías, fittings y válvulas de diámetros menores a 2\", ver clase ES0M.",
    "Las presiones de esta clase se limitaron a los valores del material ASTM A213 TP316L, ya que los diámetros menores se complementan con ese material.",
  ],
};

const AP0H = {
  designT: ["21"], designP: ["16,31"],
  comps: [
    c("Pipe", "HDPE High Density Polyethylene PE-100, negro, SDR 11 (PN16)", "", "", "ISO 4427 / IRAM 13485", "—", '1"–16" (32–400mm)', "(7)"),
    c("Jointing Method", "Butt Fusion", "", "", "", "—", "—", "(2)(6)"),
    c("Fittings", "HDPE High Density Polyethylene PE-100 (PN16) — inyectados o fabricados", "", "", "", "—", "—", "(5)(7)"),
    c("Stub End", "Long type full face PE-100 (PN16)", "", "", "", "—", "—", "(7)"),
    c("Flanges", "Lap joint type ASTM A105", "", "150#", "", "—", "—", ""),
    c("Closures", "Blind Flange ASTM A105", "", "150#", "", "—", "—", "(9)"),
    c("Bolts & Nuts", "ASTM A-193 Gr.B7 studs con tuercas ASTM A-194 Gr.2H, recubrimiento bituminoso de alquitrán de hulla", "", "", "", "—", "—", "(3)(10)"),
    c("Gasket", "Neopreno tipo brida, 1/8\" espesor, 250 PSI presión de trabajo, durómetro (A) 50-60, para bridas ASME B16.5 Clase 150", "", "", "", "—", "—", "(11)"),
  ],
  valves: [],
  branch: BRANCH_AP0H,
  notes: [
    "El límite máximo de temperatura está determinado por el material de la cañería y el tipo de unión.",
    "Corte y soldadura por fusión de la cañería según recomendaciones del fabricante.",
    "Verificar la longitud del espárrago según las dimensiones del stub end a proveer.",
    "Para conexiones de rama lateral, se puede usar conexión pipe-to-pipe.",
    "Para sistema de drenaje no presurizado, se puede usar fitting fabricado.",
    "Unión a tope por método de termofusión.",
    "El rating de presión de cañería y fittings debe registrarse en la documentación del fabricante.",
    "El procedimiento de prueba hidráulica debe realizarse según recomendación del proveedor de cañería y fittings.",
    "Bridas lap-joint y ciegas deben venir recubiertas de fábrica con polipropileno.",
    "Uniones enterradas con bridas lap-joint y ciegas: una vez completadas y probadas, deben protegerse contra la corrosión por uno de estos métodos — A) pintura epoxi líquida según NAG-108 subgrupo E.2/E.3, B) mantas termocontraíbles, o C) cinta anticorrosiva de uso general tipo Polyguard 660 o proveedor equivalente.",
    "Gaskets, sellos, asientos y empaquetaduras: libres de materiales con asbesto.",
    "Cañería y fittings que eventualmente deban instalarse sobre nivel de suelo deben tener protección UV.",
    "Espárragos roscados en toda su longitud, con dos tuercas hexagonales semiterminadas pesadas.",
    "Ver el manual del proveedor para los torques recomendados y la secuencia de ajuste de bridas en sistemas de polietileno.",
  ],
};

const AP0HF = {
  designT: ["21"], designP: ["16,31"],
  comps: [
    c("Pipe", "HDPE High Density Polyethylene PE-100, negro, SDR 11 (PN16)", "", "", "ISO 4427 / IRAM 13485", "—", '3"–24" (90–630mm)', "(7)"),
    c("Jointing Method", "Butt Fusion", "", "", "", "—", "—", "(2)(6)"),
    c("Fittings", "HDPE High Density Polyethylene PE-100 (PN16) — inyectados o fabricados", "", "", "", "—", "—", "(5)(7)"),
    c("Stub End", "Long type full face PE-100 (PN16)", "", "", "", "—", "—", "(7)"),
    c("Flanges", "Lap joint type ASTM A105", "", "150#", "", "—", "—", ""),
    c("Closures", "Blind Flange ASTM A105", "", "150#", "", "—", "—", "(9)(10)"),
    c("Bolts & Nuts", "ASTM A-193 Gr.B7 studs con tuercas ASTM A-194 Gr.2H, recubrimiento bituminoso de alquitrán de hulla", "", "", "", "—", "—", "(3)(13)(14)"),
    c("Gasket", "Neopreno tipo brida, 1/8\" espesor, 250 PSI presión de trabajo, durómetro (A) 50-60, para bridas ASME B16.5 Clase 150", "", "", "", "—", "—", "(11)"),
  ],
  valves: [
    v("Gate", "VGA01C009", "—", "—", "150#", "FF", '2"–18"', "(2)"),
  ],
  branch: BRANCH_Y2,
  notes: [
    "El límite máximo de temperatura está determinado por el material de la cañería y el tipo de unión.",
    "Corte y soldadura por fusión de la cañería según recomendaciones del fabricante.",
    "Verificar la longitud del espárrago según las dimensiones del stub end a proveer.",
    "Para conexiones de rama lateral, se puede usar conexión pipe-to-pipe.",
    "Para sistema de drenaje no presurizado, se puede usar fitting fabricado.",
    "Unión a tope por método de termofusión.",
    "El rating de presión de cañería y fittings debe registrarse en la documentación del fabricante.",
    "El procedimiento de prueba hidráulica debe realizarse según recomendación del proveedor de cañería y fittings.",
    "Bridas lap-joint y ciegas deben venir recubiertas de fábrica con polipropileno.",
    "Uniones enterradas con bridas lap-joint y ciegas: una vez completadas y probadas, deben protegerse contra la corrosión por uno de estos métodos — A) todos los accesorios del empalme abulonado deben limpiarse y recubrirse a fondo con asfalto u otro material anticorrosivo, o B) pintura epoxi líquida según NAG-108 subgrupo E.2/E.3.",
    "Gaskets, sellos, asientos y empaquetaduras: libres de materiales con asbesto.",
    "Todo el equipamiento, partes y accesorios deben estar listados UL o aprobados FM.",
    "Espárragos roscados en toda su longitud, con dos tuercas hexagonales semiterminadas pesadas.",
    "Ver el manual del proveedor para los torques recomendados y la secuencia de ajuste de bridas en sistemas de polietileno.",
    "Cañería y fittings que eventualmente deban instalarse sobre nivel de suelo deben tener protección UV.",
    "Válvula subterránea para servicio contra incendio — al momento de la orden de compra debe confirmarse la profundidad para la longitud del indicator post.",
  ],
};

const BS0M = {
  designT: ["-29 a 38", "50", "90"], designP: ["39,91", "39,3", "33,96"],
  comps: [
    c("Seamless Pipe", "ASTM A312 TP316L", "80S", "", "ASME B36.19M", "PE", '½"–1½"', ""),
    c("Smls Pipe Straight Nipple", "ASTM A312 TP316L", "80S", "", "ASME B36.19M", "PExNPT", '½"–1½"', "(4)(13)"),
    c("Forged Fittings", "ASTM A182 F316L", "", "3000#", "ASME B16.11", "SW / PE", '½"–1½"', ""),
    c("Flange", "ASTM A182 F316L", "", "300#", "ASME B16.5", "SW / RF", '½"–1½"', "(5)(6)"),
    c("Blind Flange", "ASTM A182 F316L", "", "300#", "ASME B16.5", "BLIND RF", '½"–2"', ""),
    c("Gaskets", "304 SS Flexible Graphite filler, 4,5mm Nom Thk., 3,2mm Compressed Thk. / CS Zinc outer ring 304 SS inner ring", "", "300#", "ASME B16.20", "—", '½"–1½"', "(8)"),
    c("Stud Bolts", "ASTM A-193 Gr.B8M CL2", "", "", "ASME B18.2.1", "—", "—", "(3)(12)"),
    c("Nuts", "ASTM A-194 Gr.8MA", "", "", "ASME B18.2.2", "—", "—", ""),
    c("Spectacle Blind", "ASTM A240 Gr.316L", "", "300#", "ASME B16.48", "RF", '1"–1½"', ""),
    c("Hex Plug Nut", "ASTM A182 F316L", "", "3000#", "ASME B16.11", "NPT", '1"–1½"', "(4)(14)"),
    c("Coupling", "ASTM A182 F316L", "", "3000#", "ASME B16.11", "SW", '1"–1½"', ""),
    c("Half Coupling", "ASTM A182 F316L", "", "3000#", "ASME B16.11", "SWxNPTF", '1"–1½"', "(4)(13)"),
    c("Drip Ring", "ASTM A182 F316L", "", "300#", "", "RF", '1"–1½"', "(7)(10)"),
    c("Dielectric Joint", "Ver Nota 9", "", "300#", "ASME B16.21", "RF", '½"–1½"', "(9)"),
    c("Olet Fittings", "ASTM A182 F316L", "", "3000#", "MSS SP-97", "SW-NPT", '½"–1½"', "(4)(5)(13)"),
    c("Swage Nipple", "ASTM A182 F316L", "", "", "MSS SP-95", "PE-NPT", '½"–1½"', "(4)(5)(13)"),
  ],
  valves: [
    v("Ball", "VBA08S001", "Full", "—", "2000 WOG", "NPT-F x PE", '½"–1½"', "2, 3, 4"),
    v("Ball", "VBA08S002", "Full", "—", "2000 WOG", "PE", '½"–1½"', "2, 3, 5"),
    v("Globe", "VGL08S001", "Reduced", "—", "800#", "SW", '½"–1½"', "2, 3"),
    v("Check", "VCK08S001", "—", "Swing", "800#", "SW", '½"–1½"', "2, 3"),
  ],
  branch: BRANCH_B3,
  notes: [
    "Extremos biselados según ASME B16.25.",
    "Derivación soldada a 45° permitida sólo para drenajes abiertos y antorcha. Requisitos de refuerzo según código de diseño.",
    "Espárragos roscados en toda su longitud, con dos tuercas hexagonales semiterminadas pesadas.",
    "Extremo NPT según ASME B1.20.1.",
    "El bore debe coincidir con el schedule de la cañería.",
    "Bridas y extremos bridados: cara serrada spiral 125–250 AARH máx.",
    "Tap hole: ½\" diám. — tipo socket weld.",
    "Gaskets, sellos, asientos y empaquetaduras: libres de materiales con asbesto.",
    "Junta dieléctrica: sólo tipo Pikotek VCS. No se permite tipo Micarta. Incluye manguito aislante, doble aislación y arandelas de acero para tipo Pikotek.",
    "Espesor mínimo de drip ring: 38,1 mm.",
    "Ver Nota General 1.",
    "Ver Nota General 2.",
    "Fittings roscados sobre process piping: sólo para termowells y venteos de prueba hidráulica.",
    "Tapones hexagonales roscados sólo para venteos y drenajes. Deben roscarse más allá de la válvula de bloqueo, fuera del process piping.",
  ],
};

const CS0M = {
  designT: ["-29 a 38", "50", "90"], designP: ["81,92", "80,5", "70,93"],
  comps: [
    c("Seamless Pipe", "ASTM A312 TP316L", "80S", "", "ASME B36.19M", "PE", '½"–1½"', ""),
    c("Smls Pipe Straight Nipple", "ASTM A312 TP316L", "80S", "", "ASME B36.19M", "PExNPT", '½"–1½"', "(4)(13)"),
    c("Forged Fittings", "ASTM A182 F316L", "", "3000#", "ASME B16.11", "SW", '½"–1½"', ""),
    c("Flange", "ASTM A182 F316L", "", "600#", "ASME B16.5", "SW / RF", '½"–1½"', "(5)(6)"),
    c("Blind Flange", "ASTM A182 F316L", "", "600#", "ASME B16.5", "BLIND RF", '½"–2"', ""),
    c("Gaskets", "304 SS Flexible Graphite filler, 4,5mm Nom Thk., 3,2mm Compressed Thk. / CS Zinc outer ring 304 SS inner ring", "", "600#", "ASME B16.20", "—", '½"–1½"', "(8)"),
    c("Stud Bolts", "ASTM A-193 Gr.B8M CL2", "", "", "ASME B18.2.1", "—", "—", "(3)(12)"),
    c("Nuts", "ASTM A-194 Gr.8MA", "", "", "ASME B18.2.2", "—", "—", ""),
    c("Spectacle Blind", "ASTM A240 Gr.316L", "", "600#", "ASME B16.48", "RF", '1"–1½"', ""),
    c("Hex Plug Nut", "ASTM A182 F316L", "", "3000#", "ASME B16.11", "NPT", '1"–1½"', "(4)(13)(14)"),
    c("Coupling", "ASTM A182 F316L", "", "3000#", "ASME B16.11", "SW", '1"–1½"', "(4)(13)"),
    c("Half Coupling", "ASTM A182 F316L", "", "3000#", "ASME B16.11", "SWxNPT", '1"–1½"', "(4)(13)"),
    c("Drip Ring", "ASTM A182 F316L", "", "600#", "", "RF", '1"–1½"', "(7)(10)"),
    c("Dielectric Joint", "Ver Nota 9", "", "600#", "ASME B16.21", "RF", '½"–1½"', "(9)"),
    c("Olet Fittings", "ASTM A182 F316L", "", "3000#", "MSS SP-97", "SW-NPT", '½"–1½"', "(4)(5)(13)"),
    c("Swage Nipple", "ASTM A182 F316L", "", "", "MSS SP-95", "PE-NPT", '½"–1½"', "(4)(5)(13)"),
  ],
  valves: [],
  branch: BRANCH_B3,
  notes: [
    "Extremos biselados según ASME B16.25.",
    "Derivación soldada a 45° permitida sólo para drenajes abiertos y antorcha. Requisitos de refuerzo según código de diseño.",
    "Espárragos roscados en toda su longitud, con dos tuercas hexagonales semiterminadas pesadas.",
    "Extremo NPT según ASME B1.20.1.",
    "El bore debe coincidir con el schedule de la cañería.",
    "Bridas y extremos bridados: cara serrada spiral 125–250 AARH máx.",
    "Tap hole: ½\" diám. — tipo socket weld.",
    "Gaskets, sellos, asientos y empaquetaduras: libres de materiales con asbesto.",
    "Junta dieléctrica: sólo tipo Pikotek VCS. No se permite tipo Micarta. Incluye manguito aislante, doble aislación y arandelas de acero para tipo Pikotek.",
    "Espesor mínimo de drip ring: 38,1 mm.",
    "Ver Nota General 1.",
    "Ver Nota General 2.",
    "Fittings roscados sobre process piping: sólo para termowells y venteos de prueba hidráulica.",
    "Tapones hexagonales roscados sólo para venteos y drenajes. Deben roscarse más allá de la válvula de bloqueo, fuera del process piping.",
  ],
};

const ES0M = {
  designT: ["-20 a 38", "50", "90"], designP: ["207,76", "204,29", "181"],
  comps: [
    c("Seamless Pipe", "ASTM A312 TP316L", "80S", "", "ASME B36.19M", "PE", '½"–1"', "(13)"),
    c("", "", "160S", "", "", "PE", '1½"', "(13)"),
    c("Smls Pipe Straight Nipple", "ASTM A312 TP316L", "80S", "", "ASME B36.19M", "PExNPT", '½"–1"', "(4)(13)"),
    c("", "", "160S", "", "", "PExNPT", '1½"', "(4)(13)"),
    c("Forged Fittings", "ASTM A182 F316L", "", "3000#", "ASME B16.11", "SW", '½"–1½"', ""),
    c("Hex Plug Nut", "ASTM A182 F316L", "", "3000#", "", "NPT", '1"–1½"', "(4)(13)(14)"),
    c("Coupling", "ASTM A182 F316L", "", "3000#", "", "SW", '1"', "(4)(13)"),
    c("", "", "", "6000#", "", "SW", '1½"', "(4)(13)"),
    c("Half Coupling", "ASTM A182 F316L", "", "3000#", "", "SWxNPT", '1"', "(4)(13)"),
    c("", "", "", "6000#", "", "SWxNPT", '1½"', "(4)(13)"),
    c("Flange", "ASTM A182 F316L", "", "1500#", "ASME B16.5", "SW / RJ", '½"–1½"', "(5)(6)"),
    c("Blind Flange", "ASTM A182 F316L", "", "1500#", "ASME B16.5", "BLIND RJ", '½"–2"', ""),
    c("Gaskets", "Octagonal Ring Joint, TP316L SS, 135 Hb máx.", "", "1500#", "ASME B16.20", "—", '½"–1½"', "(8)"),
    c("Dielectric Joint", "Ver Nota 9", "", "1500#", "ASME B16.21", "RJ", '½"–1½"', "(9)"),
    c("Stud Bolts", "ASTM A-193 Gr.B8M CL2", "", "", "ASME B18.2.1", "—", "—", "(3)(12)"),
    c("Nuts", "ASTM A-194 Gr.8MA", "", "", "ASME B18.2.2", "—", "—", ""),
    c("Spectacle Blind", "ASTM A240 Gr.F316L", "", "1500#", "ASME B16.48", "RJ", '1"–1½"', ""),
    c("Drip Ring", "ASTM A182 F316L", "", "1500#", "", "RJ", '1"–1½"', "(7)(10)"),
    c("Olet Fittings", "ASTM A182 F316L", "", "3000#", "MSS SP-97", "SW", '1"', "(4)(5)(13)"),
    c("", "", "", "6000#", "", "SW", '1½"', "(4)(5)(13)"),
    c("Swage Nipple", "ASTM A182 F316L", "", "3000#", "MSS SP-95", "PE", '½"–1½"', "(4)(5)(13)"),
  ],
  valves: [
    v("Ball", "VBA15S001", "Full", "—", "5000 WOG", "NPT-F x PE", '½"–1½"', "2, 3, 4"),
    v("Ball", "VBA15S002", "Full", "—", "5000 WOG", "PE", '½"–1½"', "2, 3, 5"),
    v("Globe", "VGL15S001", "Reduced", "—", "1500#", "SW", '½"–1½"', "2, 3"),
    v("Check", "VCK15S001", "—", "Swing", "1500#", "SW", '½"–1½"', "2, 3"),
  ],
  branch: BRANCH_B3,
  notes: [
    "Extremos biselados según ASME B16.25.",
    "Derivación soldada a 45° permitida sólo para drenajes abiertos y antorcha. Requisitos de refuerzo según código de diseño.",
    "Espárragos roscados en toda su longitud, con dos tuercas hexagonales semiterminadas pesadas.",
    "Extremo NPT según ASME B1.20.1.",
    "El bore debe coincidir con el schedule de la cañería.",
    "Bridas y extremos bridados: cara serrada spiral 125–250 AARH máx.",
    "Tap hole: ½\" diám. tipo socket weld, hasta 2\" diám. de cañería, ¾\" para diámetros mayores.",
    "Gaskets, sellos, asientos y empaquetaduras: libres de materiales con asbesto.",
    "Junta dieléctrica: sólo tipo Pikotek VCS. No se permite tipo Micarta. Incluye manguito aislante, doble aislación y arandelas de acero para tipo Pikotek.",
    "Espesor mínimo de drip ring: 38,1 mm.",
    "Ver Nota General 1.",
    "Ver Nota General 2.",
    "Fittings roscados sobre process piping: sólo para termowells y venteos de prueba hidráulica.",
    "Tapones hexagonales roscados sólo para venteos y drenajes. Deben roscarse más allá de la válvula de bloqueo, fuera del process piping.",
  ],
};

const BC6 = {
  designT: ["-29 a 38", "50", "100", "150", "200"], designP: ["52,1", "51,1", "47,5", "46", "44,7"],
  comps: [
    c("Seamless Pipe", "API 5L Gr.B", "XXS", "", "ASME B36.10M", "PE", '½"–1½"', "(1)(2)"),
    c("", "", "XXS", "", "", "BE", '2"', "(1)(2)"),
    c("", "", "160", "", "", "BE", '3"', "(1)(2)"),
    c("", "", "120", "", "", "BE", '4"', "(1)(2)"),
    c("", "", "80", "", "", "BE", '6"–8"', "(1)(2)"),
    c("", "", "60", "", "", "BE", '10"–16"', "(1)(2)"),
    c("SAWL Pipe (100% RX)", "API 5L Gr.B", "60", "", "ASME B36.10M", "BE", '14"–24"', "(1)(2)(3)"),
    c("Seamless Pipe (Nipple)", "ASTM A-106 Gr.B", "XXS", "", "ASME B36.10M", "NPT", '½"–1½"', "(4)"),
    c("Forged Fittings", "ASTM A-105", "", "6000#", "ASME B16.11", "SW", '½"–1½"', ""),
    c("", "", "", "6000#", "", "NPT", '½"–1½"', "(4)"),
    c("Wrought Pipe Fittings", "ASTM A-234 Gr.WPB", "", "", "ASME B16.9", "BW", '2"–24"', "(6)"),
    c("Flange", "ASTM A-105", "", "300#", "ASME B16.5", "SW / RF", '½"–1½"', "(6)(7)"),
    c("", "", "", "300#", "", "WN / RF", '2"–24"', "(6)(7)"),
    c("Blind Flange", "ASTM A-105", "", "300#", "ASME B16.5", "BLIND RF", '½"–24"', "(7)"),
    c("Orifice Flange", "ASTM A-105", "", "300#", "ASME B16.36", "WN / RF", '2"–24"', "(6)(7)"),
    c("Gaskets", "304 SS Flexible Graphite filler, 4,5mm Nom Thk., 3,2mm Compressed Thk. / CS Zinc outer ring 304 SS inner ring", "", "300#", "ASME B16.20", "—", '½"–24"', "(10)"),
    c("Stud Bolts", "ASTM A-193 Gr.B7-ZINC", "", "", "ASME B18.2.1", "—", "—", "(11)(16)"),
    c("Nuts", "ASTM A-194 Gr.2H-ZINC", "", "", "ASME B18.2.2", "—", "—", ""),
    c("Spectacle Blind", "ASTM A-516 Gr.70", "", "300#", "ASME B16.48", "RF", '1"–12"', ""),
    c("Paddle & Spacer Blind", "ASTM A-516 Gr.70", "", "300#", "", "RF", '14"–24"', ""),
    c("Drip Ring", "ASTM A-516 Gr.70", "", "300#", "", "RF", '1"–12"', "(8)(14)(15)"),
    c("Dielectric Joint", "Ver Nota 9", "", "300#", "ASME B16.21", "RF", '½"–24"', "(9)"),
    c("Olet Fittings", "ASTM A-105", "", "6000#", "MSS SP-97", "SW-NPT", '½"–1½"', "(4)"),
    c("", "", "", "", "", "BW", '2"–24"', ""),
    c("Swage Nipple", "ASTM A-234 Gr.WPB", "", "", "MSS SP-95", "BW-PE", '½"–4"', "(6)"),
  ],
  valves: [
    v("Ball", "VBA08C001", "Full", "—", "2000WOG", "NPT-FxPE", '½"–1½"', "1, 2, 3, 5"),
    v("Ball", "VBA08C002", "Full", "—", "2000WOG", "PE", '½"–1½"', "1, 2, 3, 4"),
    v("Ball", "VBA03C030", "Full", "—", "300#", "RF", '2"–4"', "1, 2, 3"),
    v("Ball", "VBA03C031", "Full", "—", "300#", "RF", '6"–24"', "1, 2, 3"),
    v("Ball", "VBA08C003", "Full", "—", "2000WOG", "NPT-FxPE", '½"–1½"', "1, 2, 3, 5, 6"),
    v("Ball", "VBA08C004", "Full", "—", "2000WOG", "PE", '½"–1½"', "1, 2, 3, 4, 6"),
    v("Gate", "VGA08C009", "—", "—", "800#", "SW", '½"–1½"', ""),
    v("Gate", "VGA03C009", "—", "—", "300#", "RF", '2"–24"', "HW/Gear box ≥10\""),
    v("Globe", "VGL08C011", "—", "—", "800#", "SW", '½"–1½"', "Handwheel"),
    v("Globe", "VGL03C009", "—", "—", "300#", "RF", '2"–24"', "HW/Gear box ≥8\""),
    v("Check", "VCK08C001", "—", "Swing", "800#", "SW", '½"–1½"', ""),
    v("Check", "VCK03C011", "—", "Swing", "300#", "RF", '2"–12"', ""),
  ],
  branch: BRANCH_B10A,
  notes: [
    "Extremos biselados según ASME B16.25.",
    "Cañería enterrada: coating externo, a elegir según temperatura de servicio (3LPE fusionado -40 a 85°C, o 3LPP fusionado -20 a 100°C, según NAG 108) — el proveedor debe certificar la temperatura máxima de operación.",
    "Costura recta con 100% de radiografía.",
    "Fittings roscados sobre process piping: sólo para termowells y venteos de prueba hidráulica.",
    "Válvulas de bola socket weld deben quedar en posición abierta al soldarse a la cañería, para no dañar el asiento.",
    "El bore debe coincidir con el schedule de la cañería.",
    "Bridas y extremos bridados: cara serrada spiral 125–250 AARH máx.",
    "Tap hole: ½\" diám. tipo NPT hasta 2\" diám. de cañería, ¾\" para diámetros mayores a 2\".",
    "Junta dieléctrica: sólo tipo Pikotek VCS. No se permite tipo Micarta. Incluye manguito aislante, doble aislación y arandelas de acero para tipo Pikotek.",
    "Gaskets, sellos, asientos y empaquetaduras: libres de materiales con asbesto.",
    "Espárragos roscados en toda su longitud, con dos tuercas hexagonales semiterminadas pesadas.",
    "Ver Nota General 1.",
    "Ver Nota General 7.",
    "Espesor mínimo de drip ring: 38,1 mm.",
    "Oreja de izaje requerida en tamaños 12\" y mayores.",
    "Ver Nota General 2.",
    "Sobreespesor de corrosión máximo de 6,0 mm para cañerías de ½\" y ¾\".",
  ],
};

export const CLASSES = [
  { code: "AC1", fam: "gas", detail: AC1, page: 7, mat: "C.S.", corr: "1,6mm", rating: "150#", design: "20 kg/cm² @ -29 a 38°C", services: ["Fuel Gas", "Service Air", "Starting Air", "Nitrogen", "Glycol", "Flare", "Atm. Vents", "Gas Lift", "Hydrocarbons liquid & Gas"] },
  { code: "AC3", fam: "wserv", detail: AC3, page: 11, mat: "C.S.", corr: "3,2mm", rating: "150#", design: "20 kg/cm² @ -29 a 38°C", services: ["Service Water", "Open Drain", "Close Drain", "Hydrocarbons liquid & Gas"] },
  { code: "AL1", fam: "venteo", detail: AL1, page: 15, mat: "Low T. C.S.", corr: "1,6mm", rating: "150#", design: "20 kg/cm² @ -45 a 38°C", services: ["Low Temp. Flare", "Cold Vents"] },
  { code: "AC3F", fam: "fire", detail: AC3F, page: 19, mat: "C.S. / Galv.", corr: "3,2 / 0,0mm", rating: "150#", design: "20 kg/cm² @ 0 a 38°C", services: ["Fire Water (AG wet service)"] },
  { code: "AG0F", fam: "fire", detail: AG0F, page: 22, mat: "C.S. Hot Dip Galv.", corr: "0,0mm", rating: "150#", design: "14 kg/cm² @ -29 a 38°C", services: ["Fire Water (AG dry service)"] },
  { code: "AG0", fam: "gas", detail: AG0, page: 25, mat: "C.S. Galv.", corr: "0mm", rating: "150#", design: "20 kg/cm² @ -29 a 38°C", services: ["Instrument Air"] },
  { code: "BC1", fam: "hc", detail: BC1, page: 28, mat: "C.S.", corr: "1,6mm", rating: "300#", design: "52,1 kg/cm² @ -29 a 38°C", services: ["Hydrocarbons liquid & Gas with treatment", "Hydrocarbons liquid & Gas without treatment"] },
  { code: "BC3", fam: "hc", detail: BC3, page: 32, mat: "C.S.", corr: "3,2mm", rating: "300#", design: "52,1 kg/cm² @ -29 a 38°C", services: ["Hydrocarbons liquid & Gas with treatment", "Hydrocarbons liquid & Gas without treatment"] },
  { code: "BC3A", fam: "hc", detail: BC3A, page: 36, mat: "C.S.", corr: "3,2mm", rating: "300#", design: "52,1 kg/cm² @ -29 a 38°C", services: ["Hydrocarbons liquid & Gas with sand service"] },
  { code: "CC1", fam: "hc", detail: CC1, page: 40, mat: "C.S.", corr: "1,6mm", rating: "600#", design: "104,1 kg/cm² @ -29 a 38°C", services: ["Hydrocarbons liquid & Gas with treatment"] },
  { code: "DC1", fam: "hc", detail: DC1, page: 43, mat: "C.S.", corr: "1,6mm", rating: "900#", design: "150 kg/cm² @ -29 a 65°C", services: ["Hydrocarbons Gas with treatment"] },
  { code: "AF0G", fam: "wnm", detail: AF0G, page: 47, mat: "GRP", corr: "NA", rating: "150#", design: "10,5 kg/cm² @ 0 a 80°C", services: ["Produced Water (AG & UG)"] },
  { code: "AP0X", fam: "wnm", detail: AP0X, page: 51, mat: "PEX", corr: "NA", rating: "150#", design: "16,3 kg/cm² @ 0 a 60°C", services: ["Produced Water (AG & UG)"] },
  { code: "AC1R", fam: "wepoxy", detail: AC1R, page: 55, mat: "C.S. w/ int. coating", corr: "1,6mm", rating: "150#", design: "20 kg/cm² @ -20 a 38°C", services: ["Produced Water", "Injection Water"] },
  { code: "BC1R", fam: "wepoxy", detail: BC1R, page: 59, mat: "C.S. w/ int. coating", corr: "1,6mm", rating: "300#", design: "52,1 kg/cm² @ -20 a 38°C", services: ["Produced Water", "Injection Water"] },
  { code: "DC1R", fam: "wepoxy", detail: DC1R, page: 63, mat: "C.S. w/ int. coating", corr: "1,6mm", rating: "900#", design: "156,2 kg/cm² @ -20 a 38°C", services: ["Produced Water", "Injection Water"] },
  { code: "EC1R", fam: "wepoxy", detail: EC1R, page: 67, mat: "C.S. w/ int. coating", corr: "1,6mm", rating: "1500#", design: "210,8 kg/cm² @ -20 a 38°C", services: ["Produced Water", "Injection Water"] },
  { code: "AP0H", fam: "wserv", detail: AP0H, page: 71, mat: "HDPE", corr: "0mm", rating: "150#/PN16", design: "16,31 kg/cm² @ 21°C", services: ["Service Water Underground"] },
  { code: "AP0HF", fam: "fire", detail: AP0HF, page: 74, mat: "HDPE", corr: "0mm", rating: "125/150#/PN16", design: "16,31 kg/cm² @ 21°C", services: ["Fire Water (UG wet service)"] },
  { code: "BS0M", fam: "wss", detail: BS0M, page: 77, mat: "S.S.", corr: "0,0mm", rating: "300#", design: "39,91 kg/cm² @ -29 a 38°C", services: ["Produced Water", "Injection Water", "(complementa AC1R en diámetros menores)"] },
  { code: "CS0M", fam: "wss", detail: CS0M, page: 80, mat: "S.S.", corr: "0,0mm", rating: "600#", design: "81,92 kg/cm² @ -29 a 38°C", services: ["Produced Water", "Injection Water", "(complementa BC1R en diámetros menores)"] },
  { code: "ES0M", fam: "wss", detail: ES0M, page: 83, mat: "S.S.", corr: "0,0mm", rating: "1500#", design: "207,76 kg/cm² @ -20 a 38°C", services: ["Produced Water", "Injection Water", "(complementa DC1R/EC1R en diámetros menores)"] },
  { code: "BC6", fam: "hc", detail: BC6, page: 86, mat: "C.S.", corr: "6,4mm", rating: "300#", design: "52,1 kg/cm² @ -29 a 38°C", services: ["Hydrocarbons liquid & Gas without treatment"] },
];

export const seedClasses = () => CLASSES.map((k) => ({ ...k, on: true }));
